### ISSUE TITLE
How to set a bed::Record to have start position zero (start of chromosome)

### ISSUE THREAD

**Issue by nh13** [zaeleus/noodles#100]
BED files are 0-based exclusive, so the start position of a chromosome would have zero, but `Position` is non-zero: https://github.com/zaeleus/noodles/blob/bd104ae09560da2562d92535d047e8305f4ee2d2/noodles-bed/src/record/builder.rs#L13

See Position:
https://github.com/zaeleus/noodles/blob/bd104ae09560da2562d92535d047e8305f4ee2d2/noodles-core/src/position.rs#L15

**Comment by nh13** [comment]
Are bed records 1-based inclusive in the API, but 0-based exclusive on disk?

**Comment by zaeleus** [comment]
> Are bed records 1-based inclusive in the API, but 0-based exclusive on disk?

Yes, all positions in noodles are normalized to be 1-based inclusive. This makes all intervals closed. Each format determines how the positions are read and written.

For example, BED intervals are 0-based left-closed, right-open. If the record interval is [0, 3) on disk, this is represented as [1, 3] in noodles.

**Comment by nh13** [comment]
@zaeleus this fantastic. Thank you!!!
