### ISSUE TITLE
BGZF Index

### ISSUE THREAD

**Issue by mmalenic** [zaeleus/noodles#103]
Is there any support for reading BGZF index files, that is, [.gzi files](http://www.htslib.org/doc/bgzip.html#GZI_FORMAT)? If not, is there any interest in this feature? I'd be happy to help/contribute with writing something up.

For [htsget-rs](https://github.com/umccr/htsget-rs) we are thinking of using a bgzf index to supplement other indices. This could avoid some reads/seeks to the underlying file (the file the indices are for) for certain htsget queries.

**Comment by zaeleus** [comment]
There is currently no support for BGZF indices.

Yes, if you'd like to add a reader, create it under a `gzi` module in noodles-bgzf. The index can be a simple list of position pairs. The reader can simply read the entire index into memory.

```rust
mod gzi {
    pub type Index = Vec<(u64, u64)>;

    mod reader {
        pub struct Reader<R>;

        impl Reader<R> {
            pub fn new(inner: R) -> Self;
            pub fn read_index(&mut self) -> Index;
        }
    }
}
```

**Comment by mmalenic** [comment]
I'd be interested to implement the `async` version of this too. Could I submit another PR, or create another issue for that?

**Comment by zaeleus** [comment]
A new PR referencing this issue is fine.
