### ISSUE TITLE
Region query on the bgzipped indexed fasta?

### ISSUE THREAD

**Issue by lu6huimin** [zaeleus/noodles#108]
Problem: for noodles-fasta 0.13.0, query on bgzipped indexed fasta has not yet supported, right?

Possible solution: implement `std::io::Seek` for `noodles_bgzf::Reader`.

However, it will conflict with the original `fn seek(pos: VirtualPosition)`. Is that OK to rename all `seek` of virtual position to `seek_virtual_position`, or anything else you like? I can make a draft implementation, if a pull request is welcome.

**Comment by lu6huimin** [comment]
@zaeleus Would you like to comment on this? For large genomes, fasta files are bgzipped in most cases.

**Comment by zaeleus** [comment]
noodles-fasta can now seek/query bgzipped FASTA files. See [`fasta::IndexedReader`](https://docs.rs/noodles/0.29.0/noodles/fasta/struct.IndexedReader.html) and the [`fasta_query`](https://github.com/zaeleus/noodles/blob/e8c5fe9b1c9d4cd4f8801936ea6692397c8c589c/noodles-fasta/examples/fasta_query.rs) example.

**Comment by lu6huimin** [comment]
Thanks!
