### ISSUE TITLE
Buffered reading of BGZF breaks calculation of virtual positions.

### ISSUE THREAD

**Issue by MaltheSR** [zaeleus/noodles#11]
While experimenting, I ran into a quirk in the `bgzf` module: when working with a `reader: io::BufReader<bgzf::Reader<R>>`, calls to `reader.get_ref().virtual_position()` break. A little MWE to illustrate:

```
use std::io::{self, BufRead, Read, Write};

use noodles_bgzf as bgzf;

fn log(line: &str, virtual_position: &bgzf::VirtualPosition) {
    println!(
        "Line '{}', compressed offset {}; uncompressed offset {}.",
        line, virtual_position.compressed(), virtual_position.uncompressed()
    );
}

fn main() -> io::Result<()> {
    // Setup

    let input = b"line1\nline2\nline3\nline4\nline5\n";

    let mut writer = bgzf::Writer::new(Vec::new());
    writer.write_all(input)?;
    let data = writer.finish()?;

    // Plain reader (this works as expected)

    println!("Plain reader:");

    let mut reader = bgzf::Reader::new(data.as_slice());
    let mut virtual_position = reader.virtual_position();
    let mut buf = [0u8; 6];

    while let Ok(_) = reader.read_exact(&mut buf) {
        let line = std::str::from_utf8(&buf[0..5]).expect("cannot parse UTF8");
        log(line, &virtual_position);
        virtual_position = reader.virtual_position();
    };

    println!();

    // Buffered reader (this does not work as expected)

    println!("Buffered reader:");

    let mut reader = io::BufReader::new(bgzf::Reader::new(data.as_slice()));

    loop {
        let virtual_position = reader.get_ref().virtual_position();
        let mut line = String::new();
        match reader.read_line(&mut line) {
            Ok(0) => break,
            Err(e) => return Err(e),
            _ => { line.pop(); },
        }
        log(&line, &virtual_position);
    }

    Ok(())
}
```

Running this prints:

```
Plain reader:
Line 'line1', compressed offset 0; uncompressed offset 0.
Line 'line2', compressed offset 0; uncompressed offset 6.
Line 'line3', compressed offset 0; uncompressed offset 12.
Line 'line4', compressed offset 0; uncompressed offset 18.
Line 'line5', compressed offset 0; uncompressed offset 24.

Buffered reader:
Line 'line1', compressed offset 0; uncompressed offset 0.
Line 'line2', compressed offset 46; uncompressed offset 0.
Line 'line3', compressed offset 46; uncompressed offset 0.
Line 'line4', compressed offset 46; uncompressed offset 0.
Line 'line5', compressed offset 46; uncompressed offset 0.
```

I guess this is simply a consequence of the fact that the virtual position will be moved on `BufReader::fill_buf`, since this is where the call to the inner `bgzf::Reader::read` occurs, rather than `BufReader::consume`. Therefore, I thought at first that I was perhaps in unintended territory by going through the `BufReader::get_ref`, but I notice the same thing occurs in `vcf::Reader::virtual_position`, so I thought it might be helpful to mention it here.

The only solution I could think of would be to implement `io::BufRead` on the `bgzf::Reader` directly, to ensure that the position gets updated properly in `consume`. I think that could be made to work, and in some sense it seems kind of natural since the `bgzf::Reader` is already kind of buffered via the calls to `read_block`. I'll be happy to try and help draft a PR if you think this is the way forward, but I thought maybe you might have different ideas for how and whether this should be supported.

**Comment by zaeleus** [comment]
Sorry for the delayed response (happy holidays!).

I see what's happening here, and you're correct in your reasoning. Fantastic example and investigation, by the way!

I like the initial direction of #11. I'll do a more thorough review, and, if you'd like, we can work together to finish it up.

**Comment by MaltheSR** [comment]
Sounds good, and happy holidays to you too!
