### ISSUE TITLE
Support serialization for noodles::bam::lazy::Record

### ISSUE THREAD

**Issue by kaizhang** [zaeleus/noodles#113]
I would like to perform the out-of-core sorting for large bam files. To do this, the bam records need to be serializable and will go through a round-trip of saving to the disk and then reading from it. Either one of the following will be useful:

1. Support serde's Serialize and Deserialize trait for noodles::bam::lazy::Record.
2. Expose the private fields of noodles::bam::lazy::Record, so that the user can write serialization codes themselves.

**Comment by kaizhang** [comment]
Option 1 may be too invasive, but perhaps option 2 is reasonable. After all, the lazy record itself has no guarantee that it is valid. Exposing the fields will not make it more dangerous. This has become a roadblock for me as it prevent me from implementing anything similar to "samtools sort".

**Comment by zaeleus** [comment]
Thanks for the follow up. Both `AsRef<u8>` (baaa8d9c8815359e2e2625571140239a5a43b582) and `TryFrom<Vec<u8>>` (8d807a8961fae59d7e0d25bccd4cbba6272de3ff) are now implemented.

**Comment by kaizhang** [comment]
Awesome! Thank you!
