### ISSUE TITLE
parsing VCF records fails if e.g. INFO and FORMAT meta lines in the header are interspersed

### ISSUE THREAD

**Issue by tedil** [zaeleus/noodles#114]
(This is w.r.t. noodles_vcf / noodles_bcf)
When trying to read the following **b**cf file:
```txt
##fileformat=VCFv4.3
##FILTER=<ID=PASS,Description="All filters passed">
##INFO=<ID=FIRST_INFO,Number=1,Type=String,Description="first info field definition in header">
##FORMAT=<ID=FIRST_FORMAT,Number=1,Type=String,Description="first format field definition in header">
##INFO=<ID=SECOND_INFO,Number=1,Type=String,Description="second info field definition in header">
##FORMAT=<ID=SECOND_FORMAT,Number=1,Type=String,Description="second format field definition in header">
##contig=<ID=1,length=248956422>
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample
1	3394684	foo	C	G	.	.	.	FIRST_FORMAT:SECOND_FORMAT	First:Second
```
the error `Custom { kind: InvalidData, error: "missing header FORMAT record for SECOND_INFO" }'` will be encountered during conversion from bcf record to vcf record (`record.try_into_vcf_record(header, string_maps)`).
Note that this happens during the `FORMAT` key lookup even though it's an `INFO` key (`SECOND_INFO`).
I assume this is due to the meta lines ordering -- but the VCF v4.3 specification allows header meta lines to appear in any order (with the exception of `##fileformat`, which always comes first).

**Comment by tedil** [comment]
Interestingly this specific example doesn't fail for me anymore either (not sure why, I've hence only replaced a call to `StringMaps::from(...)` with `.parse()?`).
I have now attached a file which fails for me when running the bcf_view example binary.
[example.bcf.gz](https://github.com/zaeleus/noodles/files/9706535/example.bcf.gz)

**Comment by tedil** [comment]
Ah, I think it's the `Number`s given for `SVLEN` etc are incorrect.
If that's really the case, the error should be a bit more helpful and at least include the invalid record.

**Comment by zaeleus** [comment]
Thanks for the example.

Yes, the underlying source of this error is `TryFromFieldsError::NumberMismatch` on the SVLEN INFO record, but it's being discarded and rethrown as a generic error (`header::record::ParseError`) on parse. I'll improve the error type here.

**Comment by zaeleus** [comment]
Parse errors were accidentally being discarded and are now bubbled up to the root error. In this example, it'll at least now show that an INFO record has a number mismatch: `InvalidInfo(NumberMismatch("A", "."))`. There's still room for better parse error feedback.

Thanks again for reporting!
