### ISSUE TITLE
Allow setting fasta hard wrap length

### ISSUE THREAD

**Issue by mbhall88** [zaeleus/noodles#121]
[Writing a fasta record](https://docs.rs/noodles/latest/noodles/fasta/struct.Writer.html#method.write_record) states

> Sequence lines are hard wrapped at 80 bases.

would it be possible to open this up for customisation? I don't want any wrapping in my fasta files.

**Comment by claymcleod** [comment]
Hey @mbhall88,

You should be able to get a writer that doesn't wrap by doing something like this:

```rust
let mut writer = fasta::Writer::builder(handle)
        .set_line_base_count(usize::MAX)
        .build();
```

**Comment by zaeleus** [comment]
Yes, as mentioned, the [FASTA writer builder](https://docs.rs/noodles/0.28.0/noodles/fasta/writer/struct.Builder.html) allows the line base count to be set via [`Builder::set_line_base_count`](https://docs.rs/noodles/0.28.0/noodles/fasta/writer/struct.Builder.html#method.set_line_base_count). I updated the documentation in c798863f2cfad2a05beb34aa2f3ae50aded11919 to reflect this.

Setting the line base count to `usize::MAX` will effectively disable wrapping for most sequences (i.e., most formats do not support sequences > 2<sup>31</sup> - 1 anyway), but do tell if this does not work for your use case.

**Comment by mbhall88** [comment]
Thank you both very much! Sorry, I missed the Builder section of the docs.
