### ISSUE TITLE
cram/writer: Add `cram::AsyncWriter`

### ISSUE THREAD

**Issue by claymcleod** [zaeleus/noodles#123]
An `AsyncWriter` for CRAM files is needed within [ngs](https://github.com/stjude-rust-labs/ngs) to (competitively) convert SAM/BAM files to CRAM.

**Comment by zaeleus** [comment]
An async writer was added in noodles 0.29.0/noodles-cram 0.21.0. See [`cram::AsyncWriter`](https://docs.rs/noodles/0.29.0/noodles/cram/async/struct.Writer.html).

**Comment by claymcleod** [comment]
Whoops! Didn't see that, thank you!
