### ISSUE TITLE
cram/async: support read_record

### ISSUE THREAD

**Issue by claymcleod** [zaeleus/noodles#126]
I've been using the trick you recommended in [this issue](https://github.com/zaeleus/noodles/issues/51#issuecomment-961460782) to avoid many clones. While [`bam::AsyncReader::read_record`](https://github.com/zaeleus/noodles/blob/master/noodles-bam/src/async/reader.rs#L196-L198) exists, the equivalent does not appear to exist for CRAM. Would we be able to add that method?

**Comment by zaeleus** [comment]
This is not possible to do at a record level, no. CRAM is a column-based format, and slices (a batch of records) typically require two passes to resolve mates in the same batch.

**Comment by claymcleod** [comment]
Okay I see. Thanks for the explanation!
