### ISSUE TITLE
BCF?

### ISSUE THREAD

**Issue by brainstorm** [zaeleus/noodles#13]
Hello Michael,

While writing some small tasks for GSoC students:

https://github.com/chris-zen/htsget-mvp/labels/gsoc

I've noticed that BCF is not present in Noodles's workspace. It shouldn't be a big deal since for variants we'll be focusing on VCF files in the backend, but I just wanted to ask if you have plans to implement a BCF reader in Noodles?

This is not high priority at all, I was just curious while revising [Google's htsget impl](https://github.com/googlegenomics/htsget/blob/master/internal/bcf/bcf.go).

/cc @chris-zen @victorskl

**Comment by zaeleus** [comment]
Yes, BCF will come. I find that vcf[.gz] is far more commonly used, so BCF has been low priority.

Progress can be tracked in the [`bcf`](https://github.com/zaeleus/noodles/tree/bcf) branch.

**Comment by zaeleus** [comment]
A BCF 2.2 reader and writer is now in `master`.
