### ISSUE TITLE
alignment::reader::Builder build_from_reader cannot read from stream (e.g., stdin)

### ISSUE THREAD

**Issue by bpow** [zaeleus/noodles#130]
For reasons outlined elsewhere, it's nice to have an API for SAM/BAM/CRAM that is format-independent (#78).

I also find that it is frequently useful to be able to read from stdin. Obviously there are limitations (since stdin is not seekable, only sequential access is possible), but if can be useful if you're going to need to process all of the records anyway, or just to be able to use `pv` ahead of the process to monitor progress.

Right now, I don't think it's possible to use the format-independent API when reading from stdin because it allows for the possibility of format autodetection by reading the first few bytes of the file, then seeking back to the beginning of the file. And stdin doesn't have the `Seek` trait.

I could see two possibilities that would allow this to happen:
1. make a build_from_reader_with_format or something like that which only restricts R to `Read + 'static` rather than `Read + Seek +'static`
2. instead of seeking, convert build_from_reader to use something with the `BufRead` trait rather than `Read + Seek`, so we could call `fill_buf` to (probably?) get enough data to detect the format type without advancing the file position. I'm new enough to rust that I don't know whether this is a good idea or not.

**Comment by zaeleus** [comment]
> 2\. instead of seeking, convert build_from_reader to use something with the `BufRead` trait rather than `Read + Seek`, so we could call `fill_buf` to (probably?) get enough data to detect the format type without advancing the file position.

That's actually a pretty clever idea! I implemented this in 58a8f8e3b8985ad8a314c6afb48af9b477a02c14. It can be tested with the `util_alignment_view` example by using the conventional `-` as stdin.

```
$ cargo run --release --all-features --example util_alignment_view -- in.bam
$ cargo run --release --all-features --example util_alignment_view -- - < in.bam
```

Thanks!
