### ISSUE TITLE
panic when removing SAM tags

### ISSUE THREAD

**Issue by d-cameron** [zaeleus/noodles#132]
```
#[test]
fn should_add_remove_tags() {
    let mut r = Record::builder()
        .set_data(noodles::sam::record::Data::try_from(vec![
            Field::new(Tag::AlignmentHitCount, Value::Int32(1)),
            Field::new(Tag::EditDistance, Value::Int32(1)),
            Field::new("aa".parse().unwrap(), Value::Int32(1)),
            Field::new("ab".parse().unwrap(), Value::Int32(1)),
            Field::new("ac".parse().unwrap(), Value::Int32(1)),
        ]).unwrap()).build();
    r.data_mut().remove("aa".parse().unwrap());
    r.data_mut().remove("ab".parse().unwrap());
    r.data_mut().remove("ac".parse().unwrap());
}
```

Expected behavior:
The 3 tags in question are removed.

Actual behavior:
thread 'should_add_remove_custom_tags' panicked at 'index out of bounds: the len is 3 but the index is 3', .....\noodles-sam-0.21.0\src\record\data.rs:254:34

**Comment by d-cameron** [comment]
Any particular reason you didn't go with a tree (BST or btree) on the [u8;2] tag value? There aren't many possible tags so the depth won't get very deep. 

Alternatively, when the Vec is short, direct traversal is probably going to be the fastest lookup approach.

They both seem like they'd be be simpler than standard vs non-standard split parallel implementation you currently have and don't have the fixed 55*u16=110 byte overhead of StandardFieldIndices.

**Comment by zaeleus** [comment]
#49 explains the design decision, but in hindsight, I overcomplicated it, blinded by performance numbers. 😅

I've fixed this issue for now, but I agree there should be further exploration to simplify it. I do want to eventually get rid of `Field`, and use `Data` like a normal key-value map.

Thanks a lot for reporting!
