### ISSUE TITLE
noodles bgzf: Reader breaks on concatenated bgzip files

### ISSUE THREAD

**Issue by omicsorama** [zaeleus/noodles#133]
If you `concat` multiple `bgzip`-ed fastq.gz files together into a single file, the noodles bgzf Reader (sync version) via Builder and multiple (>1) workers, stops reading without an error after the first set of reads from the first fastq.gz file. For example, the attached file was generated by `concat` two different bgzip'ed files (each with 10k reads) into a single file. There should be a total number of 20k reads but the bgzf reader stops iterating records after the first 10k reads without an error

thanks for the great library and any help would be appreciated
[Undetermined_S0_L001_R1_10k+10k.fastq.gz](https://github.com/zaeleus/noodles/files/10016527/Undetermined_S0_L001_R1_10k%2B10k.fastq.gz)

**Comment by omicsorama** [comment]
Thanks! When do you think a new version will be pushed to crates.io?

**Comment by zaeleus** [comment]
[noodles 0.30.0](https://crates.io/crates/noodles/0.30.0)/[noodles-bgzf 0.18.0](https://crates.io/crates/noodles-bgzf/0.18.0) is now released.

**Comment by omicsorama** [comment]
Amazing much appreciated
