### ISSUE TITLE
Question about async read bam

### ISSUE THREAD

**Issue by nihilee** [zaeleus/noodles#140]
Dear developer, I am confused about bam read async api, will it speed up reading bam file? what is the difference between using the api and use non-async api then create threads manually?

**Comment by zaeleus** [comment]
If you have very low I/O latency, async I/O is generally not beneficial. The blocking and async APIs are identical in functionality, so it's up to the user to choose the one that fits their application.

See also "[When not to use Tokio](https://tokio.rs/tokio/tutorial#when-not-to-use-tokio)" in the Tokio tutorial.

**Comment by nihilee** [comment]
@zaeleus Thanks for your answer~, so according to my understand, the async api is used for low I/O latency and provide a easy-used tokio threadpool?

**Comment by zaeleus** [comment]
Yes, that's commonly the use case.
