### ISSUE TITLE
Making an BED reader where number of columns unknown

### ISSUE THREAD

**Issue by Euphrasiologist** [zaeleus/noodles#141]
Hi, 

I've tried making a generic BED reader, which can read in a file, check number of columns, and then use the appropriate reader. But I'm finding this really difficult to do with the current API. Something like this:

```rust
use noodles::bed::Reader

let mut reader = bed::Reader::new(bytes);

let mut columns = String::new();
reader.read_line(&mut columns).unwrap();
let column_number = columns.split_whitespace().collect::<Vec<&str>>().len();

let reader_records = match column_number {
  3 => reader.records::<3>(),
  4 => reader.records::<4>(),
  ... etc...
  12 => reader.records::<12>(),
};

```

Or am I approaching this wrong!? 

Thanks,
M

**Comment by Euphrasiologist** [comment]
(That code snippet above fails, I should have mentioned that)

**Comment by zaeleus** [comment]
For BED, the format _must_ be known beforehand. Counting the number of fields cannot distinguish between, e.g., BED4 and BED3+1. I would recommend assuming the input to be BED3 if the number of fields is unknown.

**Comment by Euphrasiologist** [comment]
Great, thank you! I think I had assumed this much, given the barrage of compiler errors 😅
