### ISSUE TITLE
Accessing (potentially missing) tags and reading values

### ISSUE THREAD

**Issue by jamestwebber** [zaeleus/noodles#15]
Hey there! I've got a BAM-parsing pipeline that I'd love to re-implement in Rust using `noodles` to speed everything up and consolidate many steps.

I've been reading through the code/documentation/examples, which are all great! But I either haven't found or haven't grokked how to a) check for the presence of a tag and b) get the value in an efficient way.

Using `pysam` the workflow would be something like (for example):

```python
for a in aligned_bam:
   if a.is_secondary or a.is_supplementary or a.mapping_quality < mq:
       continue
   for tag in tags:  # I have a list of tags I'm looking for
       if a.has_tag(tag):
           tag_histograms[tag][a.get_tag(tag)] += 1
```

I'm not sure how I would do this with `noodles`. My current guess is

```rust
for result in reader.records() {
    let record = result?;        
    let flags = record.flags();
    let data = record.data();

    if !(flags.is_supplementary() || flags.is_duplicate()) {
        let mapq = u8::from(record.mapping_quality());

        if mapq != 255 && mapq >= 10 {
            // iterate over data and add values to counters?
        }
    }
}
```

In part I'm questioning whether I need to iterate over the tags or if there's a faster lookup method. That's about where I decided to open an issue.

Happy to contribute examples for this workflow, if you can point me in the right direction!

**Comment by zaeleus** [comment]
Hi, @jamestwebber!

`bam::record::Data::fields` returns an iterator over the data fields (effectively, `Iterator<Item = io::Result<bam::record::data::Field>>`). This allows an end user to choose the most efficient lookup method for their use case. For example, a linear search would perform better than creating an entire map for a single tag lookup.

In your case, I would suggest creating and using a map for multiple lookups. You can either create one with the BAM data fields

```rust
let data: HashMap<_, _> = record
    .data()
    .fields()
    .map(|result| result.map(|field| (field.tag().clone(), field))) 
    .collect::<Result<_, _>>()?;
```

or convert it to SAM data, which is stored as a tag-field map.

```rust
let data = sam::record::Data::try_from(bam_record.data())?;
```

With this, you can

> a) check for the presence of a tag

```rust
data.contains_key(&Tag::AlignmentScore);
```

> b) get the value in an efficient way

```rust
let value = data.get(&Tag::AlignmentScore).map(|field| field.value());
```

The Rust code using noodles then becomes similar to your Python example.

```rust
let tags = [
    Tag::MinMappingQuality,
    Tag::AlignmentScore,
    // ...
];

for result in reader.records() {
    let record = result?;
    let flags = record.flags();

    let is_low_quality = record
        .mapping_quality()
        .map(|mapq| mapq < MIN_MAPPING_QUALITY)
        .unwrap_or(true);

    if flags.is_secondary() || flags.is_supplementary() || is_low_quality {
        continue;
    }

    let data = sam::record::Data::try_from(record.data())?;

    for tag in &tags {
        if let Some(field) = data.get(tag) {
            let value = field.value();
            // ...
        }
    }
}
```

**Comment by jamestwebber** [comment]
Thanks for the thorough explanation! I just needed to get my head back into Rust-space, where stuff like this is going to be faster than I think. 😁 

When I have something working I'll drop by again in case you'd like it as an example.

**Comment by jamestwebber** [comment]
Update: works beautifully, thanks for your help!

Some lessons learned/possible enhancements:
 - I was looking for custom tags, not the standard ones, so the SAM approach didn't work for me (at least, I didn't get it to work)
 - Tag doesn't implement `Hash` which means I couldn't use it as the keys for a hashmap. Easy enough to convert them, but might be worth adding to the library.
 - I was getting some crazy/inscrutable errors until I figured out that I needed to explicitly read the header and reference sequences before I could call `reader.records()`. I don't know if that's intended behavior? If so, it would be nice to add more informative error message (I was getting some weird slice error). But it would also be nice if `records()` skipped over that stuff if it needed to.

I think the code I have now is too complex to be a useful example, but if you'd like me to write up this use-case with a smaller version, I'm happy to open a PR.

**Comment by zaeleus** [comment]
> I was looking for custom tags, not the standard ones, so the SAM approach didn't work for me (at least, I didn't get it to work)

Custom tags can be represented using the [`Tag::Other`](https://github.com/zaeleus/noodles/blob/cd4b93ce7f211e5db1d0416957541ae64f2427ef/noodles-sam/src/record/data/field/tag.rs#L133-L134) variant. You usually want to create it by parsing a raw string, e.g.,

```rust
"ZN".parse::<Tag>()? // => Tag::Other(String::from("ZN"));
```

> Tag doesn't implement `Hash` which means I couldn't use it as the keys for a hashmap. Easy enough to convert them, but might be worth adding to the library.

[`Tag` (quite recently) implements `Hash`](https://github.com/zaeleus/noodles/blob/cd4b93ce7f211e5db1d0416957541ae64f2427ef/noodles-sam/src/record/data/field/tag.rs#L11). Sorry, I should have noted to update to this revision before.

> I was getting some crazy/inscrutable errors until I figured out that I needed to explicitly read the header and reference sequences before I could call `reader.records()`. I don't know if that's intended behavior?

Yes, this is intended. I prefer to avoid any implicit I/O. The [documentation mentions where the cursor should be](https://github.com/zaeleus/noodles/blob/master/noodles-bam/src/reader.rs#L188-L189) before calling the method, but I agree the error message is non-obvious, given it's a standard [`io::Error`](https://doc.rust-lang.org/std/io/struct.Error.html) message. I'll consider adding more explicit read errors.

**Comment by jamestwebber** [comment]
> [`Tag` (quite recently) implements `Hash`](https://github.com/zaeleus/noodles/blob/cd4b93ce7f211e5db1d0416957541ae64f2427ef/noodles-sam/src/record/data/field/tag.rs#L11). Sorry, I should have noted to update to this revision before.

Hah yes that _is_ quite recent! 😂 Nice, makes things a little cleaner.

> Yes, this is intended. I prefer to avoid any implicit I/O.
Makes sense and that's on me for not reading the documentation (I figured it out from reading the examples, so partial credit maybe). I don't know how easy it is to detect this situation, but a more specific message would be nice for people like me who don't RTFM up front.

**Comment by mbhall88** [comment]
@zaeleus your responses are always so elegant and informative. I wonder if you might include some short examples in the documentation for this kind of use case. For example I find myself commonly need to check if a tag is present for a record, and then do something different depending on the answer.
