### ISSUE TITLE
Publishing noodles-htsget

### ISSUE THREAD

**Issue by mmalenic** [zaeleus/noodles#155]
Is there any interest in publishing noodles-htsget so that it could be used as a dependency?

Some of the structs in `noodles-htsget` overlap with the structs in [`htsget-rs`](https://github.com/umccr/htsget-rs), and `htsget-rs` could use them instead of defining it's own. Specifically, [`Format`](https://github.com/zaeleus/noodles/blob/968ef33434e957c733fda3b647e52eb4b62ad33c/noodles-htsget/src/format.rs#L3-L15), [`Payload`](https://github.com/zaeleus/noodles/blob/968ef33434e957c733fda3b647e52eb4b62ad33c/noodles-htsget/src/request/payload.rs#L10-L19), [`Error`](https://github.com/zaeleus/noodles/blob/968ef33434e957c733fda3b647e52eb4b62ad33c/noodles-htsget/src/response/error.rs#L24-L30), [`Class`](https://github.com/zaeleus/noodles/blob/968ef33434e957c733fda3b647e52eb4b62ad33c/noodles-htsget/src/response/ticket.rs#L8-L13), [`BlockUrl`](https://github.com/zaeleus/noodles/blob/968ef33434e957c733fda3b647e52eb4b62ad33c/noodles-htsget/src/response/ticket.rs#L15-L21), [`Ticket`](https://github.com/zaeleus/noodles/blob/968ef33434e957c733fda3b647e52eb4b62ad33c/noodles-htsget/src/response/ticket.rs#L33-L38), [`TicketResponse`](https://github.com/zaeleus/noodles/blob/968ef33434e957c733fda3b647e52eb4b62ad33c/noodles-htsget/src/request/builder.rs#L69-L72), could be used in place of htsget-rs structs and enums. Along with making some of these non-`pub` structs `pub`, `noodles-htsget` could be published and used as a library to support this.

**Comment by zaeleus** [comment]
noodles-htsget 0.1.0 was published with noodles 0.35.0. However, I'm not sure if it'll be useful for a server implementation, as its intent is to be used as a client.
