### ISSUE TITLE
Fast copying of bam files

### ISSUE THREAD

**Issue by jdidion** [zaeleus/noodles#156]
My use case is merging multiple bam files all with identical headers. I want to use noodles as a convenient way to write the output file header and then copy records from the input files into the output file. It looks like with lazy records this can be very fast since there is no time spent decoding/encoding. It would be nice to have a `write_lazy_record` method on `Writer` to make this simple and safe. In the absence of that, I just want to make sure my approach is correct and will result in a valid merged file:

1. Open output file writer and write header
2. For each input file
    1. Open input file reader
    2. Create a mutable `lazy::Record`
    3. Continually call `read_lazy_record` on the reader until it returns `0`
    4. Write the lazy record's bytes to the writer's underlying stream

Thanks!

**Comment by zaeleus** [comment]
By merging, do you mean appending each files' records to a single output (à la [`samtools cat`](https://www.htslib.org/doc/samtools-cat.html)) or interleaving records in some sorted order (à la [`samtools merge`](https://www.htslib.org/doc/samtools-merge.html))?

**Comment by jdidion** [comment]
Appending to a single output.

**Comment by zaeleus** [comment]
In that case, you don't actually have to read the rest of the data as records. For each input, after reading the header, copy the raw byte stream to the BGZF encoder. I added an example of this in [`noodles-bam/examples/bam_cat.rs`](https://github.com/zaeleus/noodles/blob/a3ded0a5dd235a0ba2bb693f3918fa55b7d6861c/noodles-bam/examples/bam_cat.rs).

**Comment by jdidion** [comment]
Oh yes that's much better. Thanks!
