### ISSUE TITLE
Support querying for SAM/GTF/GFF records 

### ISSUE THREAD

**Issue by claymcleod** [zaeleus/noodles#158]
Currently,  `noodles::sam::Reader.records()`, `noodles::gff::Reader.records()`, and `noodles::gtf::Reader.records()` do not support querying of `noodles::core::region::Region`s like BAM and CRAM do. I'm intuiting the reason why is because they do not have the specialized indexes like BAM/CRAM do. However, it would be really nice for noodles to provide the functionality of querying a region for these files, even if it required making some generic index for the files before querying.

Required for https://github.com/stjude-rust-labs/ngs/issues/18 and https://github.com/stjude-rust-labs/ngs/issues/19.

**Comment by zaeleus** [comment]
noodles 0.25.0/noodles-sam 0.17.0 (2022-07-05) introduced a query iterator to query SAM ([`sam::Reader::query`](https://docs.rs/noodles/0.39.0/noodles/sam/struct.Reader.html#method.query)).

noodles 0.39.0/noodles-gff 0.12.0/noodles-gtf 0.10.0 (2023-05-18) now have query iterators to query GFF ([`gff::Reader::query`](https://docs.rs/noodles/0.39.0/noodles/gff/struct.Reader.html#method.query)) and GTF ([`gtf::Reader::query`](https://docs.rs/noodles/0.39.0/noodles/gtf/struct.Reader.html#method.query)).

noodles 0.39.0/noodles-csi 0.18.0 (2023-05-18) also has a generic indexed record parser ([`IndexedRecords`](https://docs.rs/noodles/0.39.0/noodles/csi/io/struct.IndexedRecords.html)) and filter ([`FilterByRegion`](https://docs.rs/noodles/0.39.0/noodles/csi/io/struct.FilterByRegion.html)).

```rust
let records = Query::new(&mut decoder, chunks)
    .indexed_records(&header)
    .filter_by_region(&region);

for result in records {
    let record = result?;
    // ...
}
```

This pattern is wrapped by [`tabix::io::IndexedReader`](https://docs.rs/noodles/0.39.0/noodles/csi/io/struct.IndexedReader.html).

```rust
let reader = tabix::io::IndexedReader::new(inner, index);
for result in reader.query(&region) {
    let record = result?;
    // ...
}
```
