### ISSUE TITLE
FASTQ description

### ISSUE THREAD

**Issue by juliangehring** [zaeleus/noodles#161]
I'm a bit surprised about the current formatting of optional descriptions in the `fastq` crate. Would be happy about any insights or inputs.

The current formatting of the FASTQ writer is:

> @{name}
> {sequence}
> +{description}
> {qualities}

I would however expect that the description is appended to the first line, equivalent to FASTA files. While there is unfortunately no official spec for the FASTQ format, the format outlined in e.g. https://en.wikipedia.org/wiki/FASTQ_format is in my experience the de-facto standard that is widely used (e.g. https://docs.rs/bio/latest/bio/io/fastq/struct.Record.html#method.fmt-1 and others).

> Field 1 begins with a '@' character and is followed by a sequence identifier and an optional description (like a [FASTA](https://en.wikipedia.org/wiki/FASTA_format) title line).
Field 2 is the raw sequence letters.
Field 3 begins with a '+' character and is optionally followed by the same sequence identifier (and any description) again.
Field 4 encodes the quality values for the sequence in Field 2, and must contain the same number of symbols as letters in the sequence.

which would yield one of the following:

> @{name} {description}
> {sequence}
> +
> {qualities}

> @{name} {description}
> {sequence}
> +{name} {description}
> {qualities}

They same could apply to the the FASTQ reader as well.

Thank you for the amazing crate and all the effort that has been put into creating it!

**Comment by zaeleus** [comment]
noodles 0.36.0/noodles-fastq 0.7.0 changes how the description is read and written, as discussed above. Thanks again for bringing this up!

> Outside of the scope of this issue, but simply thinking out aloud: It could be a nice opportunity to use a similar Record interface for FASTQ, as currently used for FASTA

`fastq::Record` remains unchanged in 0.7.0, but yes, the name and description can be modeled as a definition like in noodles-fasta. Tracked in #165.
