### ISSUE TITLE
Support for more structural variant (sub) types?

### ISSUE THREAD

**Issue by holtgrewe** [zaeleus/noodles#163]
I believe the following from VCF 4.4 cannot be represented in the `ALT` header lines.

![image](https://user-images.githubusercontent.com/521780/233022790-0154b308-9165-4b86-9253-b2bdbd43c7fd.png)

Because the type enum is

```rust
/// A VCF alternate bases allele structural variant symbol type.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum Type {
    /// A deletion (`DEL`).
    Deletion,
    /// A insertion (`INS`).
    Insertion,
    /// A duplication (`DUP`).
    Duplication,
    /// An inversion (`INV`).
    Inversion,
    /// A copy number variation (`CNV`).
    CopyNumberVariation,
    /// A breakend (`BND`).
    Breakend,
}
```

Is this correct?

**Comment by zaeleus** [comment]
The first-level types (`DEL`, `INS`, `DUP`, `INV`, and `CNV`) are supported, as noted, via [`structural_variant::Type`](https://docs.rs/noodles/0.35.0/noodles/vcf/record/alternate_bases/allele/symbol/structural_variant/enum.Type.html); and subtypes do not have constraints (`Vec<String>`). This is modeled by [`StructuralVariant`](https://docs.rs/noodles/0.35.0/noodles/vcf/record/alternate_bases/allele/symbol/struct.StructuralVariant.html). The example for [`StructuralVariant::subtypes`](https://docs.rs/noodles/0.35.0/noodles/vcf/record/alternate_bases/allele/symbol/struct.StructuralVariant.html#method.subtypes) shows `DEL:ME`:

```rust
use noodles_vcf::record::alternate_bases::allele::symbol::{
    structural_variant::Type,
    StructuralVariant,
};

let structural_variant = StructuralVariant::new(
    Type::Deletion,
    vec![String::from("ME")],
);

assert_eq!(structural_variant.subtypes(), [String::from("ME")]);
```

**Comment by holtgrewe** [comment]
OK, this is the first argument to `Builder::add_alternative_allele()`. How do I create the second? For breakends, I have:

```rust
let bnd_id = Symbol::StructuralVariant(StructuralVariant::from(Type::Breakend));
let bnd_alt = Map::<AlternativeAllele>::new("Breakend");
```

**Comment by holtgrewe** [comment]
Scratch that, it's obvious.
