### ISSUE TITLE
Implement Debug for Sample?

### ISSUE THREAD

**Issue by holtgrewe** [zaeleus/noodles#164]
Hi, what about derive'ing the Debug trait for `Sample`?

```rust
/// A VCF record genotype sample.
pub struct Sample<'g> {
    keys: &'g Keys,
    values: &'g [Option<Value>],
}
```

**Comment by zaeleus** [comment]
Thanks, this was an oversight. Added in 2d821a0296c77c8ff98de604d17184649504a919.

In the interim, `Keys` and `Option<Value>` do already implement `Debug` and can be formatted individually, e.g., `dbg!((sample.keys(), sample.values()))`;
