### ISSUE TITLE
Accessing VCF record ID?

### ISSUE THREAD

**Issue by holtgrewe** [zaeleus/noodles#168]
Could you give an example for accessing the ID of a VCF record?

**Comment by juliangehring** [comment]
Hi @holtgrewe, would the [`Ids`](https://docs.rs/noodles/latest/noodles/vcf/struct.Record.html#method.ids) method work for your use case? Below a simple example, based on the vcf-view example:

```rust
use std::env;

use noodles::vcf;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let src = env::args().nth(1).expect("missing src");

    let mut reader = vcf::reader::Builder::default().build_from_path(src)?;
    let header = reader.read_header()?;

    for result in reader.records(&header) {
        let record = result?;
        println!("ID: {}", record.ids());
    }

    Ok(())
}
```

**Comment by holtgrewe** [comment]
@juliangehring indirectly - yes. However, this uses the `Display` implementation of the `Ids` type. I would like to get individual `String`s out of it.

**Comment by juliangehring** [comment]
Okay, I see. Iterating over the `Ids` yields individual `Id`s that can be converted into `String`s, e.g.

```rust
let ids: Vec<_> = record.ids().iter().map(|x| x.to_string()).collect();
```

Maybe something around those lines?

**Comment by holtgrewe** [comment]
@juliangehring wonderful, that does the trick.

I have to say that I find it pretty hard to derive such things from the docs as these nested sets/maps in noodles_vcf are hard to grok from there. It reminds me a bit of my C++ days. ;-)

**Comment by zaeleus** [comment]
@holtgrewe, if you ever get stuck or have questions, please don't hesitate to ask. I recently opened up [project discussions](https://github.com/zaeleus/noodles/discussions) for its Q&A category.
