### ISSUE TITLE
gtf reader failed when there is no semicolon after the last attribute 

### ISSUE THREAD

**Issue by DongzeHE** [zaeleus/noodles#169]
Hello,

Thanks for providing such an excellent tool!

I am processing a GTF file that does not have a semicolon at the end of each line. One record from the file looks like the following

```
1       havana  gene    29554   31109   .       +       .       gene_id "ENSG00000243485"; gene_version "5"; gene_name "MIR1302-2HG"; gene_source "havana"; gene_biotype "lincRNA"
```

`noodles`'s GTF reader threw an error when parsing this file because of the missing `;`. As this is not a rare case ([the GTF file](https://support.10xgenomics.com/single-cell-gene-expression/software/downloads/3.0#:~:text=References%20%2D%203.0.0%20(November%2019%2C%202018)) I am using is pretty widely used), do you think that it is possible to make the gtf reader handle this exception internally, for example appending a `;` if there is not one at the end of a line, or something more elegant?  
 

Best,
Dongze

**Comment by zaeleus** [comment]
Thanks for the link to the example data. I would indeed consider the one included (at least) with the GRCh38 references to be an invalid GTF file.

noodles-gtf is based on http://mblab.wustl.edu/GTF22.html, which requires the semicolon:

> Attributes must end in a semicolon which must then be separated from the start of any subsequent attribute by exactly one space character (NOT a tab character).

Funnily, [UCSC's example for GTF](https://genome.ucsc.edu/FAQ/FAQformat.html#format4) doesn't have a terminator for the last attribute but also links to the same document. For a different reason, [their GTF files](https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/genes/) are also invalid.

Given the lack of conformance and no definitive specification, the attributes parser is now more relaxed to accept these as inputs in 6308b118f0488630554d8174a139b3892f4bf3f9.
