### ISSUE TITLE
`noodles_fasta::reader::records::Records` returns an error on empty lines

### ISSUE THREAD

**Issue by jch-13** [zaeleus/noodles#189]
I'm using the `noodles_fasta::reader::records::Records` Iterator to read the hg19 reference FASTA file provided by the 1KGP (ftp://ftp-trace.ncbi.nih.gov/1000genomes/ftp/technical/reference/human_g1k_v37.fasta.gz). Right after the `MT` sequence, this files contains an empty line which causes the Iterator to fail [parsing the `Definition`](https://github.com/zaeleus/noodles/blob/c5aadc5f659a13da1ba826a98463b748472fd7b7/noodles-fasta/src/reader/records.rs#L44), returning an `io::Error` with `ErrorKind::InvalidData`.

I wonder whether returning Errors on empty lines is the intended behavior of this Iterator? And what's the proper way of ignoring specifically this error type without also ignoring other `InvalidData` cases?

**Comment by zaeleus** [comment]
Thanks for reporting this example. There's evidence that it was poorly joined from multiple sources, and I'm surprised existing FASTA parsers accept empty lines.

I'll change the sequence reader to also skip empty lines.

**Comment by zaeleus** [comment]
This is now changed in noodles 0.46.0 / noodles-fasta 0.27.0.

**Comment by jch-13** [comment]
Thank you!
