### ISSUE TITLE
Scope question: index creation

### ISSUE THREAD

**Issue by slazicoicr** [zaeleus/noodles#2]
The crates currently offers read and write functionality for various file formats and their respective index formats. Is it within the scope of this repo to include an `Indexer` struct to calculate the index `Record` from the respecitve file format?

**Comment by zaeleus** [comment]
Hi @slazicoicr!

Yes, index builders are on the todo list, particularly for BAM.

**Comment by zaeleus** [comment]
As of 221bb0980f971ec3b75e867568ef82a6d1bafa9e, BAM, CRAM, FASTA, and FASTQ have indexers. GFF, SAM, and VCF can be indexed via tabix. If there are any further problems with indexing, please submit a new issue.

Thanks again to @slazicoicr for working on the FASTA indexer (#4)!
