### ISSUE TITLE
sam/record/data/field/tag: Add const initializer

### ISSUE THREAD

**Issue by zaeleus** [zaeleus/noodles#204]
> How do we avoid the `.parse().unwrap()` on?  I'd like to have the whole expression be constant.
> 
> ```rust
>     data.insert(
>         "x1".parse().unwrap(),
>         noodles::sam::record::data::field::Value::from(value),
>     );
> ```

_Originally posted by @nh13 in https://github.com/zaeleus/noodles/issues/197#issuecomment-1724912818_

---

`sam::record::data::field::Tag` should have a `const fn` initializer to use in const contexts, e.g.,

```rust
const X1: Tag = match Tag::new([b'X', b'1']) {
    Some(tag) => tag,
    None => unreachable!(),
};

data.insert(X1, Value::from(0));
```

**Comment by nh13** [comment]
Thank you! Wow!

**Comment by zaeleus** [comment]
This is [now available](https://docs.rs/noodles/0.52.0/noodles/sam/record/data/field/tag/enum.Tag.html#method.new) in noodles 0.52.0 / noodles-sam 0.43.0.
