### ISSUE TITLE
How to extract pileup information from a bam file?

### ISSUE THREAD

**Issue by huangnengCSU** [zaeleus/noodles#205]
Hi,
    I am attempting to replace rust-htslib with noodles in my code. But I am unsure of how to extract the pileup information from a bam file. In rust-htslib, the method is as follows:
```
use rust_htslib::{bam, bam::Read};

let mut bam = bam::Reader::from_path(&"test/test.bam").unwrap();

// pileup over all covered sites
for p in bam.pileup() {
    let pileup = p.unwrap();
    println!("{}:{} depth {}", pileup.tid(), pileup.pos(), pileup.depth());

    for alignment in pileup.alignments() {
        if !alignment.is_del() && !alignment.is_refskip() {
            println!("Base {}", alignment.record().seq()[alignment.qpos().unwrap()]);
        }
        // mark indel start
        match alignment.indel() {
            bam::pileup::Indel::Ins(len) => println!("Insertion of length {} between this and next position.", len),
            bam::pileup::Indel::Del(len) => println!("Deletion of length {} between this and next position.", len),
            bam::pileup::Indel::None => ()
        }
    }
}
```

best,
Neng

**Comment by zaeleus** [comment]
While noodles does have a simple pileup iterator to calculate depth at each position (see [`noodles-bam/examples/bam_depth.rs`](https://github.com/zaeleus/noodles/blob/71b513cb0afe2e874ec795ec47fb8992086e549c/noodles-bam/examples/bam_depth.rs)), it does not provide a more sophisticated engine like htslib.

You may be interested in tools like [perbase](https://github.com/sstadick/perbase).

**Comment by huangnengCSU** [comment]
Thank you!
