### ISSUE TITLE
Nondeterministic TBI index creation

### ISSUE THREAD

**Issue by holtgrewe** [zaeleus/noodles#213]
I believe the use of `HashMap` in the following place in `noodles-csi/src/index/reference_sequence.rs` create nonderministic behaviour when creating TBI indices. I observe this when creating indices of the same `.vcf.gz` file multiple times and comparing the resulting binary index files.

```
/// A CSI reference sequence.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ReferenceSequence {
    bins: HashMap<usize, Bin>,
    linear_index: Vec<bgzf::VirtualPosition>,
    metadata: Option<Metadata>,
}
```

**Edit** -- probably, `indexmap::IndexMap` would be a better choice here?

**Comment by zaeleus** [comment]
Agreed, this can be changed to an ordered map to preserve insertion order, which will allow indices to be (re)serialized in the same way. Thanks for the suggestion!
