### ISSUE TITLE
Build Error on Windows

### ISSUE THREAD

**Issue by tshauck** [zaeleus/noodles#217]
Hi thanks again for this package... just wanted to mention that the latest release seems to fail to build on windows. The root cause looks to be a new file named `aux.rs`, which I think can't be named `aux` due to it being a reserved word in windows.

From my build pipeline on windows:

<img width="863" alt="image" src="https://github.com/zaeleus/noodles/assets/421839/770301ab-8f99-457c-aefb-a14daeeca5e9">

A reference from a bit of searching about: https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions

<img width="799" alt="image" src="https://github.com/zaeleus/noodles/assets/421839/7ab83e6a-e991-47b3-80a2-66dd1df7ac8c">

happy to help update things if I can, thanks again!

**Comment by zaeleus** [comment]
Thanks for reporting! The aux module is now renamed header, as it's effectively the only known type of optional data.

noodles 0.59.0 / noodles-csi 0.28.0 is published with this fix.
