### ISSUE TITLE
BGZF invalid header really strict

### ISSUE THREAD

**Issue by andypexai** [zaeleus/noodles#237]
My noodles program processing some `.fastq.gz` files would work really well if I could bypass [the error if this isn't valid](https://github.com/zaeleus/noodles/blob/8c7014cf8b129a223a7bf8d608be35dd2b8eb253/noodles-bgzf/src/reader/block.rs#L115-L149).  Could it be possible to make it a warning or an optionally-bypassed requirement?  My files are generated with Illumina's "bcl-convert" and have the right gzip magic numbers and the CM value is also 8, but the other numbers are off.  I get a hard error here, but HTSlib reads them just fine.  Even `bgzip --test my.fastq.gz` runs without a warning or anyting.

**Comment by zaeleus** [comment]
It sounds like your files are gzip-compressed, not bgzip-compressed. Can you share the first 18 bytes of an input, e.g., `head -c 18 <src> | xxd`?

**Comment by andypexai** [comment]
```
00000000: 1f8b 0800 0000 0000 04ff b4bd 498e 2b49  ............I.+I
00000010: 1260                                     .`
```

After `bgzip -d` and `bgzip`

```
00000000: 1f8b 0804 0000 0000 00ff 0600 4243 0200  ............BC..
00000010: 5700                                     W.
```

I think it'd be strange if they're regular gzipped.  In the C++ predecessor program we have, using [hts_set_threads()](https://github.com/samtools/htslib/blob/5d2c3f721d78906486f1759b8cda87649a14c684/htslib/hts.h#L707) had a dramatic benefit for us.  I think they're are a sorta botched Illumina bgzipping that still is functional.  I wish I had more details about what bcl-convert 4.0.3 is attempting to do.  I think the previous [bcl2fastq also had issues](https://github.com/samtools/samtools/issues/1467).  I haven't seen the bgzip people discuss this particular issue but it's not making errors there, just here.

**Comment by ghuls** [comment]
You can run `file` or `htsfile` from HTSlib on your file.
```
# bgzipped files have the "extra field" section compared with most normal gzipped files.
$ file test.fastq.gz
test.fastq.gz: gzip compressed data, extra field, original size 23124

$ htsfile test.fastq.gz
test.fastq.gz:   FASTQ BGZF-compressed sequence data
```

**Comment by andypexai** [comment]
OK that's pretty definitive then.  It just says "gzipped-compressed".  I suppose the C++ program I was talking about the gains were for compression-only and I had this confused.  Thanks.

**Comment by zaeleus** [comment]
Thanks for the output, @andypexai. It does show that your inputs are gzip-compressed, not bgzip-compressed. The fourth byte `FLG.FEXTRA` is not set, meaning the frame metadata is missing.

I also confirmed that bcl-convert 4.0.3 does _not_ write bgzip-compressed output.[^1]

```
$ bcl-convert --version
bcl-convert Version 00.000.000.4.0.3
Copyright (c) 2014-2018 Illumina, Inc.

$ htsfile results/*.fastq.gz
results/Undetermined_S0_L001_R1_001.fastq.gz:   FASTQ gzip-compressed sequence data
results/Undetermined_S0_L001_R2_001.fastq.gz:   FASTQ gzip-compressed sequence data
results/iseq-DI_S1_L001_R1_001.fastq.gz:    FASTQ gzip-compressed sequence data
results/iseq-DI_S1_L001_R2_001.fastq.gz:    FASTQ gzip-compressed sequence data
```

Instead of using noodles-bgzf, use a general-purpose decoder like [async-compression](https://crates.io/crates/async-compression).

```rust
// cargo add async-compression flate2 --features async-compression/gzip,flate2/zlib-ng

use tokio::io::AsyncBufRead;
use async_compression::futures::bufread::GzipDecoder;

let mut reader = File::open(input_file)
    .await
    .map(BufReader::new)
    .map(GzipDecoder::new)
    .map(BufReader::new)
    .map(fastq::AsyncReader::new)?;
```

Note that async-compression uses [flate2](https://github.com/rust-lang/flate2-rs). I would recommend linking to [zlib-ng](https://github.com/zlib-ng/zlib-ng) for better performance, 



[^1]: "[Generating FASTQs with BCL Convert (Illumina Software)](https://www.10xgenomics.com/support/software/cell-ranger/latest/analysis/inputs/cr-direct-demultiplexing-bcl-convert#example-dataset)". Accessed 2024-02-28.

**Comment by andypexai** [comment]
@zaeleus That's actually exactly what I tried, but now it's a 

```
Error: Kind(UnexpectedEof)
```

and now I'm hunting down something else that probably isn't related to noodles.

**Comment by gtamazian** [comment]
Just to comment on the issue: as @zaeleus mentioned, bgzip compression of output FASTQ files was removed from the Illumina BCL Convert software starting from version 4.0 (see "Changes from bcl2fastq" for feature "FASTQ Compression Specification" in [Illumina Knowledge Article #3710](https://knowledge.illumina.com/software/general/software-general-reference_material-list/000003710)). I experienced the same issue with an unexpected end-of-file and solved it using `MultiGzDecoder` from the [flate2](https://crates.io/crates/flate2) library, see [flate2: About multi-member Gzip files](https://docs.rs/flate2/latest/flate2/index.html#about-multi-member-gzip-files).
