### ISSUE TITLE
query causes a panic

### ISSUE THREAD

**Issue by CastilloDel** [zaeleus/noodles#25]
When calling query on a ReferenceSequence from a Tabix file ([this file](https://github.com/umccr/htsget-rs/blob/variants/data/vcf/sample1-bcbio-cancer.vcf.gz.tbi) specifically) I got a panic.
Code:
```rust
  let path = std::env::current_dir()
    .unwrap()
    .join("data")
    .join("vcf")
    .join("sample1-bcbio-cancer.vcf.gz.tbi");

  let index = tabix::read(path).unwrap();
  for ref_seq in index.reference_sequences() {
    ref_seq.query(150, i32::MAX);
  }
```
Output:
```
thread 'main' panicked at 'index out of bounds: 37450 >= 37450', /home/daniel/.cargo/registry/src/github.com-1ecc6299db9ec823/bit-vec-0.6.3/src/lib.rs:539:9
```
It seems to have something to do with the i32::MAX value, but it doesn't happen if the start value is 0
I also wanted to ask if there is an easy way of suing the query functionality with an open end or start, so it covers until the end of the sequence or the start.

**Comment by zaeleus** [comment]
Despite positions being integers with a max value of 2<sup>31</sup> - 1, the largest supported position in a tabix index (min shift = 14, max depth = 5) is actually 2<sup>(14 + 3 * 5)</sup> - 1 = 2<sup>29</sup> - 1. The max bin ID, including the metadata pseudo-bin, is then 2<sup>(3 * (5 + 1))</sup> / 7 + 1 = 37450, which explains the panic.

A start position of 0 currently causes bin calculations to be skipped and returns an incorrect, empty list.

I added guards and the method is now fallible in 6b8e0ea4895968339dfbd6f799b480d57bc5b93f.

> I also wanted to ask if there is an easy way of suing the query functionality with an open end or start, so it covers until the end of the sequence or the start.

In 6d66ecb27f54e1374a3f5fa3c857c9500d6e4578, the interface for `query` changed to accept a [`RangeBounds`](https://doc.rust-lang.org/std/ops/trait.RangeBounds.html), which allows the use of any [range expression](https://doc.rust-lang.org/reference/expressions/range-expr.html). To update, change usages of `query(start, end)` to `query(start..=end)`. In your example, an unbounded end would be `req_seq.query(150..)`.

**Comment by CastilloDel** [comment]
That seems great. Love the changes! Thanks!

**Comment by CastilloDel** [comment]
One thing: Wouldn't make sense to have `noodles_bam::bai::index::reference_sequence::ReferenceSequence::query` also work the same way?

**Comment by zaeleus** [comment]
> One thing: Wouldn't make sense to have `noodles_bam::bai::index::reference_sequence::ReferenceSequence::query` also work the same way?

Yes, the interface is now consistent across BAI, CSI, and tabix: <https://github.com/zaeleus/noodles/compare/1da8dcc8c66a6fc3f922a09e44cc0e6e3296df63...988ade3eb013ca3ab681d4cbf876ad06930d5609>.
