### ISSUE TITLE
Docs typo

### ISSUE THREAD

**Issue by Crispy13** [zaeleus/noodles#252]
In https://docs.rs/noodles/latest/noodles/bam/index.html,

```
use noodles_bam as bam;
```

May it need to be modified to `use noodles::bam as bam;`?

**Comment by zaeleus** [comment]
This is not an error. When using the noodles meta crate, you would indeed import using the re-exported names, e.g., `noodles::bam`. The examples, however, are written with respect to their individual crates, e.g., if you added `noodles_bam` directly as a dependency.

It's recommended to use the meta crate [as described in the README](https://github.com/zaeleus/noodles/tree/noodles-0.68.0?tab=readme-ov-file#usage).
