### ISSUE TITLE
About method names of `noodles_sam::alignment::record::Flags`

### ISSUE THREAD

**Issue by Crispy13** [zaeleus/noodles#253]
Hi.

How would you feel about renaming flag getter names according to [https://broadinstitute.github.io/picard/explain-flags.html](https://broadinstitute.github.io/picard/explain-flags.html)?

For example, `is_segmented()` will be renamed to `is_paired()`.

I think it would be good for noob bioinformaticians like me.

Also, do you have any rules for contributing this repo?
If so, I may try to pull request a little for some functions in htsjdk(SamReadGroup, unclipped_pos, etc.)

Thanks

**Comment by zaeleus** [comment]
noodles uses the terminology defined by the SAM format specification. See § 1.4.2 "[The alignment section: mandatory fields: FLAGS](https://samtools.github.io/hts-specs/SAMv1.pdf#subsection.1.4)" (2023-05-24) for flag descriptions.

It is not a design goal of noodles to copy or follow the API of existing libraries. It should provide a foundation to allow you to achieve writing those functions in your own applications. If you have questions on the availability of certain features, do feel free to start a new [discussion](https://github.com/zaeleus/noodles/discussions).

**Comment by Crispy13** [comment]
Ah, I see. But some libraries (htsjdk, pysam, rust-htslib) seems to use the names in the site I linked.

Or It may be good to write other names on doc comments of the methods.
