### ISSUE TITLE
Unexpected EOF on BCF File

### ISSUE THREAD

**Issue by tshauck** [zaeleus/noodles#255]
Hi, I'm getting `Error: Kind(UnexpectedEof)` when trying to use the async BCF example here: https://github.com/zaeleus/noodles/blob/master/noodles-bcf/examples/bcf_count_async.rs using both of the attached files (note: I added .txt extensions so GH would support the upload).

Happy to look deeper if you can repro the issue, but thought I'd bring it up here in case it's clear to you what the issue might be. Thanks!

* [index.bcf.txt](https://github.com/zaeleus/noodles/files/15064574/index.bcf.txt)
* [t.bcf.txt](https://github.com/zaeleus/noodles/files/15064588/t.bcf.txt)

**Comment by zaeleus** [comment]
Thanks for reporting! This was accidentally introduced in noodles 0.69.0/noodles-bcf 0.50.0 (https://github.com/zaeleus/noodles/commit/f72bddaddc9270cecc59cf1b0343e75a65d69f31) when a proper EOF check was implemented. It is now fixed in noodles 0.70.0/noodles-bcf 0.51.0.

**Comment by tshauck** [comment]
Thanks!
