### ISSUE TITLE
How to set tag with value in noodles::bam?

### ISSUE THREAD

**Issue by Crispy13** [zaeleus/noodles#258]
I've read [the doc of `Data`](https://docs.rs/noodles/latest/noodles/bam/record/struct.Data.html), 

but it seems that no set method is there.

**Comment by zaeleus** [comment]
Alignment format records ([`sam::Record`](https://docs.rs/noodles/0.70.0/noodles/sam/struct.Record.html), [`bam::Record`](https://docs.rs/noodles/0.70.0/noodles/bam/struct.Record.html), and [`cram::Record`](https://docs.rs/noodles/0.70.0/noodles/cram/struct.Record.html)) are immutable.

You can convert these to alignment record buffers ([`sam::alignment::RecordBuf`](https://docs.rs/noodles/0.70.0/noodles/sam/alignment/struct.RecordBuf.html)) using [`RecordBuf::try_from_alignment_record`](https://docs.rs/noodles/0.70.0/noodles/sam/alignment/struct.RecordBuf.html#method.try_from_alignment_record) to mutate the record, e.g.,

```rust
// cargo add noodles@0.70.0 --features bam,sam

use std::io;

use noodles::{
    bam,
    sam::{
        self,
        alignment::{record::data::field::Tag, record_buf::data::field::Value},
    },
};

fn main() -> io::Result<()> {
    let header = sam::Header::default();
    let record = bam::Record::default();

    let mut record_buf = sam::alignment::RecordBuf::try_from_alignment_record(&header, &record)?;

    record_buf
        .data_mut()
        .insert(Tag::COMMENT, Value::from("noodles"));

    Ok(())
}
```

If you are going to mutate every record, consider reading records as `RecordBuf` using [`Reader::read_record_buf`](https://docs.rs/noodles/0.70.0/noodles/bam/io/struct.Reader.html#method.read_record_buf)/[`Reader::record_bufs`](https://docs.rs/noodles/0.70.0/noodles/bam/io/struct.Reader.html#method.record_bufs), e.g.,

```rust
// cargo add noodles@0.70.0 --features bam,sam

use std::io;

use noodles::{
    bam,
    sam::alignment::{record::data::field::Tag, record_buf::data::field::Value},
};

fn main() -> io::Result<()> {
    let mut reader = bam::io::reader::Builder.build_from_path("in.bam")?;
    let header = reader.read_header()?;

    for result in reader.record_bufs(&header) {
        let mut record = result?;

        record
            .data_mut()
            .insert(Tag::COMMENT, Value::from("noodles"));
    }

    Ok(())
}
```

For future questions, consider posting [a discussion](https://github.com/zaeleus/noodles/discussions) under [the Q&A category](https://github.com/zaeleus/noodles/discussions/categories/q-a).

**Comment by Crispy13** [comment]
Thanks
