### ISSUE TITLE
Error while reading a BCF header

### ISSUE THREAD

**Issue by CastilloDel** [zaeleus/noodles#26]
While trying to read the header from [this file](https://github.com/umccr/htsget-rs/blob/bcf/data/bcf/vcf-spec-v4.3.bcf.gz) I got an error. (The uncompressed version can be found in the same directory)
Code:
```rust 
  let mut reader = File::open(path.as_ref()).map(bcf::Reader::new)?;

  let _ = reader.read_header().unwrap();
```
Output: 
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" }'
```
I'm not sure if this is a noodles bug, but I think so, because I created the BCF file converting [this VCF file](https://github.com/umccr/htsget-rs/blob/bcf/data/vcf/spec-v4.3.vcf.gz) using [bcftools](http://www.htslib.org/doc/bcftools.html), so it should be okay.

**Comment by MaltheSR** [comment]
The docs on `read_header` states that "The position of the stream is expected to be directly after the file format.", and the following seems to work for me:

```
use std::{fs::File, io};

use noodles::bcf;

fn main() -> io::Result<()> {
    let path = "/path/to/vcf-spec-v4.3.bcf.gz";

    let mut reader = File::open(path).map(bcf::Reader::new)?;

    let _format = reader.read_file_format();

    let header = reader.read_header()?;

    println!("{:?}", header);

    Ok(())
}
```

**Comment by CastilloDel** [comment]
MB, I missed that part on the documentation. Thanks for taking the time to answer!
