### ISSUE TITLE
Reading entries of file into preallocated buffer

### ISSUE THREAD

**Issue by rickymagner** [zaeleus/noodles#260]
Hi, I was wondering if it's possible (or on the roadmap to add) to iterate over lines of a file and store the results into a preallocated buffer? For example, the `rust_htslib` library has a [method](https://docs.rs/rust-htslib/latest/rust_htslib/bam/trait.Read.html#tymethod.read) for reading from a BAM directly into a `Record` object that's been preallocated. In just doing something silly like taking the sum of all TLEN's in a file, this seemed to be 3x faster than `noodles` for a small BAM I tried it out on. It'd be great if `noodles` could offer a similar API for iterating over entries of files so new memory doesn't need to be allocated on every line.

**Comment by zaeleus** [comment]
Yes, it's possible to reuse a [`bam::Record`](https://docs.rs/noodles/0.72.0/noodles/bam/struct.Record.html) buffer via [`Reader::read_record`](https://docs.rs/noodles/0.72.0/noodles/bam/io/struct.Reader.html#method.read_record), e.g.,

```rust
let mut record = bam::Record::default();

while reader.read_record(&mut record)? != 0 {
    // ...
}
```

**Comment by rickymagner** [comment]
Great, thanks! Also I think the difference in speed was mostly due to extra noodles verification (which I've seen talked about in other issues). I tried the hts version without using the preallocated buffer and it was still much faster, but understand this library strives for accuracy in handling the format over speed in some cases (which is a valid choice).

**Comment by zaeleus** [comment]
I would expect noodles to be quite competitive in the summation of a single field. Feel free to post the benchmark in [a discussion](https://github.com/zaeleus/noodles/discussions) if you'd like to investigate further.
