### ISSUE TITLE
Add Async GFF Reader and/or expose lazy record from string?

### ISSUE THREAD

**Issue by tshauck** [zaeleus/noodles#262]
Hi,

I wanted to ask about either adding an async GFF reader and/or making it possible to create a lazy gff record from a string.

I'd like to use the lazy GFF record with an async data source, but am having trouble because [`read_lazy_record`](https://github.com/zaeleus/noodles/blob/7bd2b6e82357970dd0331645c8d5e7bf9795235c/noodles-gff/src/reader.rs#L146-L172) seems to be the only [way to create a lazy record](https://github.com/zaeleus/noodles/blob/master/noodles-gff/src/lazy/record.rs), but because there's no async GFF reader it can't be used in my situation (S3 files). Right now, I'm just reading lines through a regular async reader then parsing via `noodles::gff::Line::from_str`.

Would you be open to having noodles do either of these things? I'd be happy to implement, but wanted to ask before I did the work.

Happy to provide more details if helpful, thanks!

**Comment by zaeleus** [comment]
I do have a basic async GFF reader implemented on a local branch. I'll merge that and get it to parity. Thanks for asking!

**Comment by zaeleus** [comment]
An async GFF reader is now available in noodles 0.73.0/noodles-gff 0.32.0.
