### ISSUE TITLE
Can support flush method on writer ?

### ISSUE THREAD

**Issue by sharkLoc** [zaeleus/noodles#269]

**Comment by zaeleus** [comment]
Use `Writer::get_mut` to the get the underlying writer that implements [`std::io::Write`](https://doc.rust-lang.org/std/io/trait.Write.html), which has a flush method, e.g.,

```
let writer = Writer::new(io::sink());
writer.get_mut().flush()?;
```

**Comment by sharkLoc** [comment]
I did a test but dose not work
![捕获](https://github.com/zaeleus/noodles/assets/50580507/9bf6613a-ba17-4981-bd08-d478e4ef33e2)

**Comment by zaeleus** [comment]
I see; thanks for the follow up. This is missing from the FASTA index writer. It's now added in ce7e5879a5a4eadfc8a73de0f8d29a042df8612a.

Do note that it's common for buffered writers to best-effort flush and close on drop, which may be a usable workaround.
