### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by CastilloDel** [zaeleus/noodles#27]
While compiling an updated version (c235259f) I got the following error
```rust
error[E0277]: the type `[u8]` cannot be indexed by `(Bound<usize>, Bound<usize>)`
   --> /home/daniel/.cargo/git/checkouts/noodles-f00ebc122d065317/c235259/noodles-fasta/src/reader.rs:251:36
    |
251 |         Ok(Record::new(definition, sequence[range].to_vec()))
    |                                    ^^^^^^^^^^^^^^^ slice indices are of type `usize` or ranges of `usize`
    |
    = help: the trait `SliceIndex<[u8]>` is not implemented for `(Bound<usize>, Bound<usize>)`
    = note: required because of the requirements on the impl of `std::ops::Index<(Bound<usize>, Bound<usize>)>` for `Vec<u8>`
```

**Comment by zaeleus** [comment]
Given [tests pass for this commit](https://github.com/zaeleus/noodles/runs/3015151119), it must be a new Rust feature, and indeed it is. Added in [1.53.0](https://github.com/rust-lang/rust/releases/tag/1.53.0):

> [You can now index into slices using (Bound<usize>, Bound<usize>).](https://github.com/rust-lang/rust/pull/77704)

Although you can update Rust to fix the compilation error, I made a small change in 0968ee6fdf70eaf6d183ba7ce33929c6481b9f8f to make it work with older versions.

Note that noodles currently does not have a minimum supported Rust version (MSRV) policy; I typically track the latest stable release.

**Comment by CastilloDel** [comment]
I'm sorry, that was my bad :( I thought I had the latest version, anyway thanks for answering and the changes!
