### ISSUE TITLE
How to write custom bam records

### ISSUE THREAD

**Issue by SteampunkIslande** [zaeleus/noodles#274]
Hello !

First, thank you to all the contributors for this awesome rust crate :)

Sadly, I'm struggling with some basic BAM file editing...
Below is a minimal example:

```rust
fn main()
{
    let mut reader = bam::io::reader::Builder::default().build_from_path(input_path)?;
    let mut writer = bam::io::writer::Builder::default().build_from_path(output_path)?;
    let header = reader.read_header()?;

    writer.write_header(&header)?;

    for result in reader.record_bufs(&header) {
        let mut record = result?;
        let tag = record.data().get(tag_name).unwrap();
        let mbc = match tag {
            noodles::sam::alignment::record_buf::data::field::Value::String(val) => {
                format!("{}", val)
            }
            _ = { String::from("") }
        };
        *record.name_mut() = Some(noodles::sam::alignment::record_buf::Name::from(
            format!("{:?}{}", record.name(), mbc).as_bytes(),
        ));
        writer.write_record(&header, record);
}
```

Here, record is of type RecordBuf, since according to what I found this is the only way to mutate BAM records (see this closed issue you answered a while ago https://github.com/zaeleus/noodles/issues/258)

Now, how can I write these modified records into a bam file? I found no way to turn RecordBuf into Record in the documentation.

Thank you for your time!

**Comment by SteampunkIslande** [comment]
Anyway, found it

https://github.com/zaeleus/noodles/discussions/240

**Comment by cademirch** [comment]
Sorry to revive this, but in #240 I don't see how you can write out the modified SAM record as BAM? Unless I'm missing something? Appreciate the help in advance!

**Comment by zaeleus** [comment]
You would use [`Writer::write_alignment_record`](https://docs.rs/noodles/0.79.0/noodles/bam/io/writer/struct.Writer.html#method.write_alignment_record), which accepts anything that implements [`sam::alignment::Record`](https://docs.rs/noodles/0.79.0/noodles/sam/alignment/trait.Record.html), e.g.,

```rust
use std::io;

use noodles_bam as bam;
use noodles_sam::{self as sam, alignment::io::Write};

fn main() -> io::Result<()> {
    let stdout = io::stdout().lock();
    let mut writer = bam::io::Writer::new(stdout);

    let header = sam::Header::default();
    writer.write_header(&header)?;

    let record = sam::alignment::RecordBuf::default();
    writer.write_alignment_record(&header, &record)?;

    Ok(())
}
```

**Comment by cademirch** [comment]
Ah got it, thank you @zaeleus!
