### ISSUE TITLE
Previously working tests now fail

### ISSUE THREAD

**Issue by CastilloDel** [zaeleus/noodles#28]
The HtsGet-rs tests fail after some of the last changes. I have tracked the new errors down to the commits mentioned in  https://github.com/umccr/htsget-rs/issues/51. It seems the changes regarding "directly reading the metadata pseudo-bin" are responsible for this. The errors vary from not being able to read index files at all and some really weird values. It would be of great help if you could look into it 🥇

**Comment by zaeleus** [comment]
Thanks for the report! These issues are fixed in https://github.com/zaeleus/noodles/compare/0968ee6fdf70eaf6d183ba7ce33929c6481b9f8f...eaedfe4000c05c9faeaf5af3cfac7815760b261c.

**Comment by CastilloDel** [comment]
That was fast! Thanks!
