### ISSUE TITLE
sam/alignment/record/sequence: Add a method signature to return a single base at a given index 

### ISSUE THREAD

**Issue by zaeleus** [zaeleus/noodles#283]
When working with implementations of [`sam::alignment::record::Sequence`](https://docs.rs/noodles/0.78.0/noodles/sam/alignment/record/trait.Sequence.htm), the bases can only be accessed via an iterator ([`Sequence::iter`](https://docs.rs/noodles/0.78.0/noodles/sam/alignment/record/trait.Sequence.html#tymethod.iter)). This is because the underlying data may not be able to be sliced, e.g., a BAM sequence that is 4-bit encoded. A method signature to return a single base at a given index should be added to the `Sequence` trait, e.g.,

```rust
pub trait Sequence {
    fn get(&self, i: usize) -> Option<u8>;
}
```

Since slicing is not required by implementations, it is only necessary for this method to receive a position and return a single base.

In the SAM, BAM, and CRAM formats, this allows for constant time lookups rather than stepping through the sequence to a particular position.

See also https://github.com/zaeleus/noodles/discussions/256#discussioncomment-10078479 by @mbhall88 for more context.

**Comment by mbhall88** [comment]
So with such an implementation you would have to call `get` in some kind of loop to get a subsequence? Could you not also accept a range and just do that work in the background?

**Comment by zaeleus** [comment]
This method is only meant to efficiently return a single base by index, not necessarily a subsequence by range.

> Could you not also accept a range and just do that work in the background?

Not directly. Adding something like `fn get<I>(&self, index: I) -> Option<&<I as SequenceIndex<[u8]>>::Output> where I: SequenceIndex<[u8]>` to the `Sequence` trait would make it lose [object safety](https://doc.rust-lang.org/reference/items/traits.html#object-safety).

I'll further investigate a new method to access a subsequence.

**Comment by mbhall88** [comment]
Oh I see. Thanks for point to that resource on object safety.
