### ISSUE TITLE
Publish a version of things on crates.io

### ISSUE THREAD

**Issue by sstadick** [zaeleus/noodles#29]
Is there a timeline or line in the sand for when you might be interested in pushing a v0.1.0 of all of these to `crates.io`? It's impossible to publish a crate that depends on any of the `noodles` family until there is a version of them in `crates.io`. 

If there's a checklist of things to add to add or do for an initial release I'm happy to help push it over the finish line. Specifically I want to release a new version of [perbase](https://github.com/sstadick/perbase/pull/38) that uses `noodles-bgzf` can't publish it to crates.io until until noodles is there first.

**Comment by brainstorm** [comment]
For now my GSoC 2021 students have been mostly using HEAD, but I agree some release model needs to happen sooner or later. 

I hope that PR #30 bootstraps this so we can have noodles over `crates.io` soon enough ;)

**Comment by zaeleus** [comment]
I'll look into publishing a release this week.

**Comment by zaeleus** [comment]
noodles is now published on crates.io: https://crates.io/crates/noodles.

**Comment by sstadick** [comment]
That's fantastic! Thank you!
