### ISSUE TITLE
gtf parse error

### ISSUE THREAD

**Issue by qingyun039** [zaeleus/noodles#291]
where read NCBI _GRCh37_latest_genomic.gtf.gz_, panic with:
`Error: Custom { kind: InvalidData, error: InvalidRecord(InvalidAttributes(InvalidEntry(Empty))) }`;

first record in _GRCh37_latest_genomic.gtf.gz_:
NC_000001.10^IBestRefSeq^Igene^I11874^I14409^I.^I+^I.^Igene_id "DDX11L1"; transcript_id ""; db_xref "GeneID:100287102"; db_xref "HGNC:HGNC:37102"; description "DEAD/H-box helicase 11 like 1 (pseudogene)"; gbkey "Gene"; gene "DDX11L1"; gene_biotype "transcribed_pseudogene"; pseudo "true"; $

**There is a space at the end of line。**

**Comment by zaeleus** [comment]
Thanks for reporting.

I suspect this is a serialization error in the GTF file, but handling such a case is undefined. To accommodate it, I changed the parser to trim trailing whitespace in 2385606b00ccb37a504d0771101a4dd66ad3a50e.

Note that the annotations are also available as GFF3 (`GRCh37_latest_genomic.gff.gz` in [`refseq_identifiers`](https://ftp.ncbi.nlm.nih.gov/refseq/H_sapiens/annotation/GRCh37_latest/refseq_identifiers/)). I highly recommend favoring GFF3, as [GTF/GFF2 is deprecated](https://gmod.org/wiki/GFF2#gff2-is-deprecated).
