### ISSUE TITLE
Should writing Strings to INFO be escaped

### ISSUE THREAD

**Issue by holtgrewe** [zaeleus/noodles#300]
Hi, when writing a STRING value to an INFO field that contains a semicolon `;` then this file cannot be imported any more.

Should I escape this in my code using noodles-vcf or should noodles do it?

**Comment by zaeleus** [comment]
Thanks for the report.

The output is correct. Semicolons (`;`) in info string values are being percent-encoded to `%3B` (e.g., "a;b" => "a%3Bb"). However, [`vcf::Record`](https://docs.rs/noodles/0.80.0/noodles/vcf/struct.Record.html) is not decoding them, which in turn makes the writer, essentially, double encode.

The buffered record reader ([`Reader::read_record_buf`](https://docs.rs/noodles/0.80.0/noodles/vcf/io/struct.Reader.html#method.read_record_buf) and [`Reader::record_bufs`](https://docs.rs/noodles/0.80.0/noodles/vcf/io/struct.Reader.html#method.record_bufs)) can be used as a workaround for now.

**Comment by zaeleus** [comment]
This is now fixed in noodles 0.81.0 / noodles-vcf 0.64.0.
