### ISSUE TITLE
VCF Sample columns

### ISSUE THREAD

**Issue by ACEnglish** [zaeleus/noodles#304]
Hello again,

Thanks again for the library. It has helped my tool development so much that I'm now applying it to VCFs with thousands of samples. However, this is causing a new problem. When I'm parsing a VCF with many samples and a dozen or so FORMAT fields, the memory usage is exploding. But my program doesn't need the FORMAT fields and actually clears all the SAMPLES in the output.

Do you have recommendations on the cleanest way to drop all sample information from a VCF? I know pysam has e.g. `pysam.VariantFile("input.vcf.gz", drop_samples=True)`, but before I request a niche feature, I was hoping there was an easy recommendation  to directly manipulate the Record's Samples similar to how the vcf header has a `header.sample_names_mut().clear()`

Have a great day,
~/Adam English

**Comment by zaeleus** [comment]
There is currently no way to drop samples when reading. There are some workarounds though.

If you're reading mutable records ([`vcf::variant::RecordBuf`](https://docs.rs/noodles/0.83.0/noodles/vcf/variant/struct.RecordBuf.html)), you can overwrite the existing samples by setting an empty [`Samples`](https://docs.rs/noodles/0.83.0/noodles/vcf/variant/record_buf/struct.Samples.html), e.g.,

```rust
*record.samples_mut() = vcf::variant::record_buf::Samples::default();
```

If you're reading immutable records ([`vcf::Record`](https://docs.rs/noodles/0.83.0/noodles/vcf/struct.Record.html)), you can create a layer that delegates all fields but samples, e.g.,

<details><summary><code>vcf_drop_samples.rs</code></summary>

```rust
use std::{
    env,
    io::{self, BufWriter},
};

use noodles_core as core;
use noodles_vcf::{self as vcf, variant::io::Write};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let src = env::args().nth(1).expect("missing src");

    let mut reader = vcf::io::reader::Builder::default().build_from_path(src)?;
    let mut header = reader.read_header()?;

    header.sample_names_mut().clear();

    let stdout = io::stdout().lock();
    let mut writer = vcf::io::Writer::new(BufWriter::new(stdout));

    writer.write_header(&header)?;

    for result in reader.records() {
        let record = result.map(RecordSansSamples)?;
        writer.write_variant_record(&header, &record)?;
    }

    Ok(())
}

struct RecordSansSamples(vcf::Record);

impl vcf::variant::Record for RecordSansSamples {
    fn reference_sequence_name<'a, 'h: 'a>(&'a self, _: &'h vcf::Header) -> io::Result<&'a str> {
        Ok(self.0.reference_sequence_name())
    }

    fn variant_start(&self) -> Option<io::Result<core::Position>> {
        self.0.variant_start()
    }

    fn ids(&self) -> Box<dyn vcf::variant::record::Ids + '_> {
        Box::new(self.0.ids())
    }

    fn reference_bases(&self) -> Box<dyn vcf::variant::record::ReferenceBases + '_> {
        Box::new(self.0.reference_bases())
    }

    fn alternate_bases(&self) -> Box<dyn vcf::variant::record::AlternateBases + '_> {
        Box::new(self.0.alternate_bases())
    }

    fn quality_score(&self) -> Option<io::Result<f32>> {
        self.0.quality_score()
    }

    fn filters(&self) -> Box<dyn vcf::variant::record::Filters + '_> {
        Box::new(self.0.filters())
    }

    fn info(&self) -> Box<dyn vcf::variant::record::Info + '_> {
        Box::new(self.0.info())
    }

    fn samples(&self) -> io::Result<Box<dyn vcf::variant::record::Samples + '_>> {
        Ok(Box::new(vcf::variant::record_buf::Samples::default()))
    }
}
```

</details>
