### ISSUE TITLE
Repeated BAM tag field: `OX`

### ISSUE THREAD

**Issue by wjwei-handsome** [zaeleus/noodles#307]
Hi @zaeleus ,

Thanks for your awesome library.

As the title says, there is a duplication of tag in the code.

In detail:

https://github.com/zaeleus/noodles/blob/435325933818ddc6ad652c22f859bc3985913300/noodles-sam/src/alignment/record/data/field/tag.rs#L24-L25

https://github.com/zaeleus/noodles/blob/435325933818ddc6ad652c22f859bc3985913300/noodles-sam/src/alignment/record/data/field/tag.rs#L144-L145

`ORIGINAL_UMI_BARCODE_SEQUENCE`: OX
`ORIGINAL_UMI_QUALITY_SCORES`: OX

Best regards,
Wenjie

**Comment by zaeleus** [comment]
Thanks for reporting!
