### ISSUE TITLE
Clarify SAM record position in docs

### ISSUE THREAD

**Issue by Daniel-Liu-c0deb0t** [zaeleus/noodles#33]
Might be a good idea to mention that the supplied position parameter for the SAM record builder must be 1-based on the docs. Also may be worthwhile to mention somewhere that the SAM position is automatically converted 0-based when writing it out as a BAM record.

**Comment by zaeleus** [comment]
I synced the position descriptions from `sam::Record`. I'll also note that [`sam::record::Position`] is inherently 1-based, so hopefully the wrapped type reduces the confusion.

[`sam::record::Position`]: https://docs.rs/noodles/0.2.0/noodles/sam/record/struct.Position.html

**Comment by Daniel-Liu-c0deb0t** [comment]
Thank you for your work on this library! I've been using it and it's really nice!
