### ISSUE TITLE
Async Readers and Send

### ISSUE THREAD

**Issue by mmalenic** [zaeleus/noodles#34]
There's and interesting barrier regarding `Send` with `AsyncReader` for the bgzf formats, and I'm not sure if it's by design. For example, the bam `AsyncReader` is not send, making code like in [this example](https://github.com/brainstorm/noodles_async_fail), fail to compile. 

The error complains that: the trait `std::marker::Send` is not implemented for `(dyn std::future::Future<Output = std::result::Result<noodles::noodles_bgzf::block::Block, std::io::Error>> + 'static)`

Do you think that this is unavoidable?

**Comment by zaeleus** [comment]
Thanks for reporting and including example code. I missed the marker for the inflater stream's `Item` type, which caused `!Send` to cascade to auto trait implementations.

Fixed in 40ac3c1fa54dbf71c045608af4a9be4d92342b01.
