### ISSUE TITLE
Async and Blocking Bam Reader VirtualPosition

### ISSUE THREAD

**Issue by mmalenic** [zaeleus/noodles#35]
It seems like the `VirtualPosition` returned by the async and blocking bam `Reader` are not the same. Have a look at [the example here](https://github.com/brainstorm/noodles_async_fail). Could be missing something, but let me know your thoughts.

**Comment by zaeleus** [comment]
Thanks for testing! Blocks weren't correctly tracking their compressed positions. This is fixed in b8af11306d3b8e01784cba7a011b7d70c856c258.
