### ISSUE TITLE
No way to mutate the flags in a SAM record

### ISSUE THREAD

**Issue by veldsla** [zaeleus/noodles#38]
The `Recod::flags` function returns `Flags` which is `Copy` so there is, as far as I can see, no way to mutate the flags.

```rust
pub fn flags_mut(&mut self) -> &mut Flags {
    &mut self.flags
}
```
is probably the way to go considering similar functions of the API. I can send a PR if you like.

**Comment by zaeleus** [comment]
> I can send a PR if you like.

Hi, @veldsla! Yes, go for it! That's exactly the signature and implementation.
