### ISSUE TITLE
INFO/MQ field type error

### ISSUE THREAD

**Issue by MaltheSR** [zaeleus/noodles#41]
I was getting an error parsing a VCF header. The code may be reduced to the following:

```rust
fn main() {
    use noodles_vcf::Header;

    let raw_header = r#"##fileformat=VCFv4.2
##INFO=<ID=MQ,Number=1,Type=Integer,Description="Average mapping quality">
"#;
    let header = raw_header.parse::<Header>();
    println!("{:?}", header); // Error
}
```

which produces `Err(InvalidInfo(TypeMismatch(Integer, Float)))`. As the error indicates, the problem seems to arise from the fact that `MQ` here is `Integer`, whereas [`noodles` seems to expect `Float`](https://docs.rs/noodles-vcf/0.7.0/src/noodles_vcf/record/info/field/key.rs.html#197). As far as I can see, the [specs](https://samtools.github.io/hts-specs/VCFv4.2.pdf) aren't entirely clear about the types of the reserved `INFO` fields. However,

1. There is in fact a note, near the end of p.6, about that the `MQ` fields for genotypes, whichs says

> MQ : RMS mapping quality, similar to the version in the INFO field. (Integer)

2. The example output files in the bcftools github consistently code `MQ` as an integer field (e.g. [here](https://github.com/samtools/bcftools/blob/9aeb1aa92e662da3baed0fe77a7b34bcde9f9b8d/test/mpileup.cAls.out))

which makes me think that MQ should perhaps be `Type::Integer` in noodles also. 

On a side note, I wonder if something similar may also be true for `BQ`, though I can find even less info in the specs and bcftools examples in this case?

Happy to submit a PR if you'd like.

**Comment by MaltheSR** [comment]
Thanks, I forgot that the latest spec was 4.3, since `bcftools` still produces 4.2 (with the offending `INFO/MQ` having `Type=Integer`) in the latest 1.13 release, which makes it hard to use noodles with anything out of `bcftools mpileup | bcftools call` currently without having to do a reheader. 

I might open an issue upstream in `bcftools` to see if anything can be done about this in the future, but having an option to somehow relax field validation would be convenient for this kind of situation in general.

**Comment by brentp** [comment]
I have a similar issue with:
```
##FORMAT=<ID=AD,Number=.,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed">
```
because (I think) noodles defines the Number for that as:
```
            Self::ReadDepths => Number::R,
```
so it gives:
```
 'error parsing header: InvalidFormat(NumberMismatch(Unknown, R))'
```

**Comment by zaeleus** [comment]
noodles 0.13.0/noodles-vcf 0.10.0 disables the type checking of INFO and FORMAT header records when the file format is < VCF 4.3.

**Comment by brentp** [comment]
Would it be possible to add this same skip for FORMAT fields?

**Comment by zaeleus** [comment]
It's also skipped for FORMAT header records in the latest version. Do you have an example of it still failing?

**Comment by brentp** [comment]
Hi, 
yes, this VCF (converted to BCF): https://github.com/brentp/vcf-bench#testing-data

with this code: https://github.com/brentp/vcf-bench/blob/625482287b6238a5d1e018ac94b3d89558593986/rust-noodles/src/main.rs

also in that code, I couldn't get the [key on line 27](https://github.com/brentp/vcf-bench/blob/625482287b6238a5d1e018ac94b3d89558593986/rust-noodles/src/main.rs#L27) to work, had to use the predefined, `Key::TotalAlleleCount`. I'm curious what I could change to use it as line 27.
