### ISSUE TITLE
Tag::Other representation

### ISSUE THREAD

**Issue by veldsla** [zaeleus/noodles#46]
I'm trying noodles-(bam/sam) for a real project now and so far the experience is more than pleasant. I've come across a few performance issues I'd like to discuss. The `Tag::Other(String)` representation being a relatively simple change.

## Problem
Currently `Tag:Other(String)` requires the end user to create a String when you want to query a tag. This has a few drawbacks
- Each tag allocates
- No constant tags because `String` cannot be `const`
- Because the bam::data::fields iterator parses every tag in the data part, searching for a specific tag can be quite expensive.

## Solution
Since the tag is required by the specification to be 2 bytes change the `String` to `[u8; 2]` (this is a `LENGTH` constant in de code).

This can be done with very few API changes and is implemented in a PR.
I ran a benchmark searching for the UMI tag in a real data line:
`AS:i:0	ZS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:75	YS:i:0	YT:Z:CP	RG:Z:000000000-JM6RV.1	XS:A:+	NH:i:4	RX:Z:CGAATAAA	MQ:i:1	MC:Z:75M	ms:i:2646`

```rust
let v = data
	.fields()
	.find_map(|f| {
		let f = f.ok()?;
		if f.tag() == &Tag::UmiSequence {
			Some(f.value().to_owned())
		} else {
			None
		}
	}).unwrap();
assert_eq!(v, Value::String("CGAATAAA".to_string()));
```
The change to `[u8; 2]` results in a decent performance gain:
```
DataValues/classic      time:   [569.66 ns 570.12 ns 570.64 ns]                                
                        change: [-28.071% -27.942% -27.830%] (p = 0.00 < 0.05)
```

## Issues
The issue with this array implementation is the same as with the String version. Directly creating the enum variant is allowed and makes it possible to generate invalid tags. `let t = Tag::Other("_a".to_string());` is currently accepted as well as in the changed version. This can probably be avoided by wrapping the array (or the String in the current version) in a newtype, but I'm not sure how this would affect the ability to make const tags. 
Let me know if you want to explore this.

**Comment by zaeleus** [comment]
Nice improvement; thanks for bringing it up! I did something similar recently to the CRAM data series encoding map (i.e., [`Vec<u8>` to `[u8; 2]`](https://github.com/zaeleus/noodles/commit/a3a8edd884532b9cafebf7254c247979e92ce042#diff-530038d5d646b952ecd64d3700ce3052da6fdd0f40178e0a5437b9c163c317b9)) but didn't think about other tags.

> Directly creating the enum variant is allowed and makes it possible to generate invalid tags.

I'm aware of this. When there are conversion functions, directly creating a variant shouldn't be relied on. Feel free to bring up a new discussion if there are any concerns.
