### ISSUE TITLE
bcf/vcf info setting, getting example

### ISSUE THREAD

**Issue by brentp** [zaeleus/noodles#52]
Hi, thanks for the library. It would be useful to have an example of setting and getting a value from the info field. I see the tests in the modules, but for a rust beginner like me, those are hard to translate to real-world. 
Also it would be useful to have a way to make the genotype parsing optional for BCFs with many samples when we only need to access the INFO fields.

**Comment by zaeleus** [comment]
Hi, @brentp!

> It would be useful to have an example of setting and getting a value from the info field.

The process to get an INFO field value involves calling `vcf::Record::info` to get the field, getting the field value, and matching the value type, e.g.,

```rust
record
    .info()
    .get(&Key::TotalDepth)
    .map(|field| field.value())
    .map(|value| match value {
        Value::Integer(n) => *n,
        _ => panic!("expected Integer, got {:?}", value),
    });
``` 

Though the interface hasn't been finalized yet, see [`noodles-vcf/src/record/info.rs`](https://github.com/zaeleus/noodles/blob/b2ca5aa061bb74db4e0eedddc6c7f21307dfaba4/noodles-vcf/src/record/info.rs) for more examples.

But note the current version of noodles-vcf has immutable records. Unfortunately, the only way to change records is to recreate the a new one using `vcf::Record::builder`, which is tedious but doable. Mutable records are on the todo.

> Also it would be useful to have a way to make the genotype parsing optional for BCFs with many samples when we only need to access the INFO fields.

Reading all fields directly from a BCF record is currently being explored, but there is no timeline for it.

**Comment by zaeleus** [comment]
> But note the current version of noodles-vcf has immutable records.

noodles 0.12.0/noodles-vcf 0.9.0 now has mutable INFO and fields, e.g.,

```rust
if let Some(dp) = record.info_mut().get_mut(&Key::TotalDepth) {
    *dp.value_mut() = Value::Integer(8);
}
```

See [`vcf::Record::info_mut`](https://docs.rs/noodles/0.12.0/noodles/vcf/struct.Record.html#method.info_mut), [`vcf::record::Info::get_mut`](https://docs.rs/noodles/0.12.0/noodles/vcf/record/struct.Info.html#method.get_mut), and [`vcf::record::Info::insert`](https://docs.rs/noodles/0.12.0/noodles/vcf/record/struct.Info.html#method.insert) for more examples.

**Comment by brentp** [comment]
excellent! I meant to get back to this after I tried it out. Will do so next week!

**Comment by brentp** [comment]
Hi, another silly rust question... How can I use this in noodles-bcf? Do I need to convert the bcf::record to a vcf::record?
I see in the docstrings that in order to mutate, it must be converted, but not for reading.

I currently see:
```
22 |         let dp = rec.info().get("AN")
   |                      ^^^^ method not found in `noodles_bcf::Record`
```

**Comment by zaeleus** [comment]
> How can I use this in noodles-bcf? Do I need to convert the bcf::record to a vcf::record?

Yes, with the exception of the chromosome/contig ID and start position, reading from a BCF record directly is not (currently) possible in noodles-bcf. There is ongoing work to do this, but for now, you have to convert it to a VCF record using [`bcf::Record::try_into_vcf_record`](https://docs.rs/noodles/0.12.0/noodles/bcf/struct.Record.html#method.try_into_vcf_record) and then read from that [record info](https://docs.rs/noodles/0.12.0/noodles/vcf/record/struct.Info.html).

**Comment by brentp** [comment]
thank you.
