### ISSUE TITLE
issues with noodles-bcf

### ISSUE THREAD

**Issue by brentp** [zaeleus/noodles#54]
Hi, I think the record size for bcf is off. With this code:
```rust
use noodles_bcf as bcf;
use std::fs::{File};
use std::io::Write;


fn main() {
    let path = &"bug.bcf";

    let mut bcf = File::open(path).map(bcf::Reader::new).expect("couldn't open bcf");
    let mut stderr = std::io::stderr();

    for r in bcf.records() {
        let mut _rec = r.expect("error getting record");
        writeln!(stderr, "made it");
    }
}
```
and the attached file (after gzipping), I get an error. The error is different (invalid record length) if the file is bigger.
[bug.bcf.gz](https://github.com/zaeleus/noodles/files/7541134/bug.bcf.gz)

Here is the error with that file:
```
thread 'main' panicked at 'error getting record: Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" }', src/main.rs:13:26
```
with a larger file, it reads 2 records and then shows:
```
thread 'main' panicked at 'error getting record: Custom { kind: InvalidData, error: "invalid record length: l_shared = 2147484031, l_indiv = 2147484031" }', src/main.rs:13:26
```

**Comment by zaeleus** [comment]
[`bcf::Reader::records`] expects the cursor to be after the header or at the start of another record. In this case, like the example in the docs, the file format and header can simply be read and discarded.

[`bcf::Reader::records`]: https://docs.rs/noodles/0.12.0/noodles/bcf/struct.Reader.html#method.records

**Comment by brentp** [comment]
doh! thanks for the help.
