### ISSUE TITLE
How to access sequence name from reference_sequence_id ?

### ISSUE THREAD

**Issue by ebioman** [zaeleus/noodles#55]
Hello
I am currently trying to get the target and mate-target ID which I find a bit confusing.
I got the header-like ReferenceSequence via:

```
    let sequences : IndexMap<String, sam::header::ReferenceSequence> = match reader.read_reference_sequences() {
        Ok(n) =>  n,
        Err(_) => panic!("ERROR: could not get ref sequence!"),
    };
```
Now I thought I could easily just look up the index and get the entry, but the `reference_sequence_id` returns something I am not familiar with:

```
let chr1_index  = read.reference_sequence_id().expect("ERROR: could not obtain read ref ID");
```
leads to 

```
[src/lib/noodles_based_lib.rs:77] chr1_index = ReferenceSequenceId(
    1434,
)
[src/lib/noodles_based_lib.rs:77] chr1_index = ReferenceSequenceId(
    1434,
)
```
Stupid question, what is that structure and how do I get the index number to use as lookup for the IndexMap ? :)

Update:
Okay stupid me figured it out, just hope that this is the good way to do it:

```
 let chr1_index  = match read.reference_sequence_id().map(i32::from){
                    Some(n) => n,
                    _ => panic!("ERROR: could not retrieve the id of the reference!"),
                };
let chr1 : &str = match seq_local.get_index(chr1_index as usize){
                    Some(n) => n.0 ,
                    None  => panic!("ERROR: could not assign a reference ID to a reference name!"),
                };
```
If this seems fine, please feel free to close. Just want to avoid that I close it and you recommend against this way ;)

**Comment by zaeleus** [comment]
[`bam::record::ReferenceSequenceId`] is a [newtype] that wraps a raw `i32` to ensure a reference sequence ID is valid, i.e., between 0 and 2<sup>31</sup> - 1, inclusive.

A BAM record does not store the reference sequence name on each record but an index of the associated reference sequence in the reference sequence dictionary.

To get the reference sequence name, you first need to convert the reference sequence ID to an `usize` for indexing. Then either use the reference sequences from the SAM header ([`sam::Header::reference_sequences`]) or the binary reference sequences ([`bam::Reader::read_reference_sequences`]) to get the corresponding [`ReferenceSequence`]. E.g.,

```rust
let reference_sequence_name = record
    .reference_sequence_id()
    .map(|id| {
        header
            .reference_sequences()
            .get_index(i32::from(id) as usize)
            .map(|(_, rs)| rs.name())
            .expect("missing reference sequence")
    })
    .unwrap_or("*");
```

[`bam::record::ReferenceSequenceId`]: https://docs.rs/noodles/0.12.0/noodles/bam/record/struct.ReferenceSequenceId.html
[newtype]: https://doc.rust-lang.org/rust-by-example/generics/new_types.html
[`sam::Header::reference_sequences`]: https://docs.rs/noodles/0.12.0/noodles/sam/struct.Header.html#method.reference_sequences
[`bam::Reader::read_reference_sequences`]: https://docs.rs/noodles/0.12.0/noodles/bam/struct.Reader.html#method.read_reference_sequences
[`ReferenceSequence`]: https://docs.rs/noodles/0.12.0/noodles/sam/header/struct.ReferenceSequence.html

**Comment by ebioman** [comment]
Thanks, I am still new to rust and didn't encounter newtype so far - used mostly structures for that purpose.
Therefore I was Abit puzzled how to deconstruct these.

**Comment by zaeleus** [comment]
For future reference, noodles 0.13.0/noodles-bam 0.9.0 implements `sam::RecordExt` for `Record`, which simplifies getting the associated reference sequence from the reference sequence dictionary. E.g., to get the reference sequence name for a record:

```rust
use noodles_sam::RecordExt;

let reference_sequence_name = record
    .reference_sequence(header.reference_sequences())
    .transpose()?
    .map(|rs| rs.name().as_str())
    .unwrap_or("*");
