### ISSUE TITLE
bcf/reader/record/site/info: Reading a field with a missing value fails

### ISSUE THREAD

**Issue by brentp** [zaeleus/noodles#56]
Hi, here is an example record:
```
chr1  27378 . T C 31.28 VQSRTrancheSNP99.80to100.00 AF_EAS_unrel=.
```

with:
```
##INFO=<ID=AF_EAS_unrel,Number=A,Type=Float,Description="Allele frequency in EAS (2504 unrelated samples)">
```

**Comment by zaeleus** [comment]
Thanks for the report!

I always made the assumption that INFO field values are mandatory. If the value is missing/unknown, the entire field is omitted.

Unfortunately, this case is undefined in the spec. I asked in https://github.com/samtools/hts-specs/issues/609 for clarification.
