### ISSUE TITLE
docs.rs fails to standalone build async crates

### ISSUE THREAD

**Issue by veldsla** [zaeleus/noodles#62]
Recent version of the async enabled crates fail to build standalone on docs.rs.

In the [logs](https://docs.rs/crate/noodles-bam/0.9.0/builds/465115) the following can be found
```
error[E0432]: unresolved import `tokio::fs`
```
bam started failing after 0.7.

When built through the wrapper noodles package the docs seem build without issues, but they are built without the async feature.

**Comment by zaeleus** [comment]
Thanks! This affected noodles-{bam,cram,csi,tabix}. The fix moves tokio's `fs` feature as a requirement from the dev dependency to the normal dependency.
