### ISSUE TITLE
Mutable access to VCF header

### ISSUE THREAD

**Issue by malthesr** [zaeleus/noodles#65]
As far as I can tell, it's currently impossible to modify an existing `vcf::Header`, apart from adding unstructured records with the `insert` method. This is inconvenient e.g. for the case when modifying an existing VCF by adding a few INFO or FORMAT fields to the header and records, rather than building a header from scratch.

I see that the `sam::Header` already has `_mut` methods for cases like this. Would it make sense to add something similar for the `vcf::Header` methods that return `IndexMap`s? For the non-`IndexMap` fields (`assembly`, `file_format`, `pedigree_db`), there could be similar `_mut` methods to return mutable reference or perhaps simply `set_` setters? Finally, it might sometimes be ergonomic to create a `vcf::header::Builder` from an existing header - perhaps `impl From<Header> for Builder` could be nice?

Happy to make the PR if you'd like.

**Comment by zaeleus** [comment]
Yes, `vcf::Header` definitely needs methods to mutate fields. I'll assign you the task.

The following should be added to return mutable references to the field:

  * `Record::file_format_mut`
  * `Record::infos_mut`
  * `Record::filters_mut`
  * `Record::formats_mut`
  * `Record::alternative_alleles_mut`
  * `Record::assembly_mut`
  * `Record::contigs_mut`
  * `Record::meta_mut`
  * `Record::samples_mut`
  * `Record::pedigrees_mut`
  * `Record::samples_names_mut`

> Finally, it might sometimes be ergonomic to create a `vcf::header::Builder` from an existing header - perhaps `impl From<Header> for Builder` could be nice?

I considered this for `sam::header::Builder` as well, but the builders in noodles are additive only. In the case of an immutable edit, cloning the header and modifying that using the mutation methods is more ideal.
