### ISSUE TITLE
noodles::fastq comment support

### ISSUE THREAD

**Issue by tedil** [zaeleus/noodles#71]
As of noodles version 0.17.0 / noodles-fastq version 0.3.0, the fastq module does not support comments at all. I know that these are rarely used, they are however part of the file format. Would it be possible to include functionality for reading/getting and writing/setting comments?

**Comment by zaeleus** [comment]
Thanks for bringing this up!

noodles 0.18.0/noodles-fastq 0.4.0 no longer discards the description field of a record. Use [`Record::description`] to read it, and [`Record::description_mut`] to modify it.

[`Record::description`]: https://docs.rs/noodles/0.18.0/noodles/fastq/struct.Record.html#method.description
[`Record::description_mut`]: https://docs.rs/noodles/0.18.0/noodles/fastq/struct.Record.html#method.description_mut
