### ISSUE TITLE
Make record attributes hashable

### ISSUE THREAD

**Issue by FelixMoelder** [zaeleus/noodles#74]
Hi!

I am currently migrating some code from rust-htslib to noodles.
While doing so it turned out that several bam and sam record attributes are no primitive times e.g. a record position and therefore do not support hashing.
As I need to add several attributes to a HashSet it would be helpful if hashing would be generally supported by deriving `Hash`
In my case this would concern `ReferenceSequenceId` and `sam::record::Position`.

**Comment by zaeleus** [comment]
`Hash` is now implemented for `bam::record::ReferenceSequenceId` (e54605f7fff0d3e5c6ed9a31e9dd363233a9731d) and `sam::record::Position` (80e58ec0f11068d76b73ab50e10269d3af9a2761). I'll avoid a blanket implementation on all fields for now, but do submit a new issue if there's another one needed.

**Comment by FelixMoelder** [comment]
Great and thank you for the quick implementation!
