### ISSUE TITLE
noodles_cram: write_record fails for reads from circular contig

### ISSUE THREAD

**Issue by tedil** [zaeleus/noodles#75]
When writing ultralong nanopore reads from circular contigs (in this specific case chrM), noodles_cram::Writer::write_record fails with
```
thread 'main' panicked at 'index out of bounds: the len is 16569 but the index is 16569', /home/till/.cargo/registry/src/github.com-1ecc6299db9ec823/noodles-cram-0.11.0/src/data_container/compression_header/preservation_map/substitution_matrix/builder.rs:17:28
```
I assume this is because the read wraps around the contig. I've attached a cram file ([failing_record.zip](https://github.com/zaeleus/noodles/files/8096476/failing_record.zip)) which contains such a record. The reference fasta is available at https://s3-us-west-2.amazonaws.com/human-pangenomics/T2T/CHM13/assemblies/chm13.draft_v1.1.fasta.gz (from the [telomere-to-telomere project](https://github.com/marbl/CHM13))

**Comment by zaeleus** [comment]
Thanks for the sample input; it's very useful!

The major issue here is that the writer builds and uses the new substitution matrix too late in the write process and is actually producing incorrect counts. Furthermore, new substitution codes are never replaced in the input record.

I'll work on this this week.

**Comment by zaeleus** [comment]
noodles 0.20.0 / noodles-cram 0.13.0 fixes the main issue of building the substitution matrix and using the new substitution codes (plus a slew of CRAM I/O fixes). It passes your sample input, but do tell if there are any other issues. Some additional notes:

  * If you're not using [`Reader::records`] but decoding raw records directly from the slice ([`Slice::records`]), you must resolve the CRAM records ([`Slice::resolve_records`]) before sending them to the writer. (This concept will likely be removed in the future.)

  * The CRAM reader and writer now use [`fasta::Repository`], a concurrent sequence cache that uses a storage adapter to look up and load sequence data. With an indexed FASTA file, you no longer have to load all the reference sequences beforehand, e.g.,

    ```rust
    let reader = File::open(fasta_src).map(BufReader::new).map(fasta::Reader::new)?;
    let index = fai::read(fasta_index_src)?;
    let adapter = IndexedReader::new(reader, index);
    let repository = fasta::Repository::new(adapter);
    ```

[`Reader::records`]: https://docs.rs/noodles/0.20.0/noodles/cram/struct.Reader.html#method.records
[`Slice::records`]: https://docs.rs/noodles/0.20.0/noodles/cram/data_container/struct.Slice.html#method.records
[`Slice::resolve_records`]: https://docs.rs/noodles/0.20.0/noodles/cram/data_container/struct.Slice.html#method.resolve_records
[`fasta::Repository`]: https://docs.rs/noodles/0.20.0/noodles/fasta/struct.Repository.html
