### ISSUE TITLE
How to create a `noodles_bam::record::Sequence` from `&str` or `&[u8]`?

### ISSUE THREAD

**Issue by jch-13** [zaeleus/noodles#76]
Hi,
first of all, thank you very much for this library!

I am currently trying to create BAM record from scratch and I'm struggling a bit.
Is there an idiomatic way to create the query sequence of a BAM record from `&str` or `&[u8]`? There is [`FromStr`](https://doc.rust-lang.org/nightly/core/str/traits/trait.FromStr.html) impl'ed for `noodles_sam::record::Sequence` so I can create SAM records, but I'm missing the path SAM -> BAM (or a direct way to create a BAM record's `Sequence`).

I hope I'm not missing anything obvious here. Thank you!

**Comment by jch-13** [comment]
Oh, nevermind, I think I found a solution:
```Rust
use noodles::{bam, sam};

let bam_seq = bam::record::Sequence::from(
    sam::record::sequence::Sequence::from_str(std::str::from_utf8(&input_record.sequence)?)?
        .iter()
        .map(Into::into)
        .collect(),
);
```
Sorry for the noise...

**Comment by zaeleus** [comment]
In noodles 0.20.0 / noodles-bam 0.16.0, [`bam::record::Sequence`] now implements [`TryFrom<&[u8]>`][try-from-u8-for-sequence], e.g.,

```rust
let sequence = bam::record::Sequence::try_from(b"ACGT")?;
```

[`bam::record::Sequence`]: https://docs.rs/noodles/0.20.0/noodles/bam/record/struct.Sequence.html
[try-from-u8-for-sequence]: https://docs.rs/noodles/0.20.0/noodles/bam/record/struct.Sequence.html#impl-TryFrom%3C%26%27_%20%5Bu8%5D%3E
