### ISSUE TITLE
bgzf/writer: Get virtual position

### ISSUE THREAD

**Issue by malthesr** [zaeleus/noodles#77]
It's sometimes desirable to be able to get the virtual position in a BGZF stream while writing to it. In htslib, I believe [`bgzf_tell`](https://github.com/samtools/htslib/blob/4289991d9c37981d6ef1c1436ec6e791d9993437/htslib/bgzf.h#L222) enables something like this for both readers and writers, but I don't think this is currently possible in `noodles_bgzf`?

Having a quick look at the current implementation, I guess supporting this would require maintaining `block_address` and `block_offset` fields (in the htslib terminology) on the `Writer`, but perhaps there's a smarter way around this.

Alternatively, downstream consumers could maintain block addresses and offsets themselves if required, but I'm not sure if currently enough information is available from the `Writer` to allow such a workaround?

What are your thoughts on whether to support something like this?

**Comment by zaeleus** [comment]
`bgzf::Writer` now tracks its position (`Writer::position`), which allows the calculation of a virtual position (`Writer::virtual_position`).
