### ISSUE TITLE
BCF read_records returns early eof error

### ISSUE THREAD

**Issue by mmalenic** [zaeleus/noodles#79]
After working on the [storage abstraction at htsget-rs](https://github.com/umccr/htsget-rs/issues/68), some tests broke when upgrading to newer versions of noodles.

Specifically, the BCF reader returns an UnexpectedEof error when reading the second record from this [file](https://github.com/umccr/htsget-rs/blob/main/data/bcf/vcf-spec-v4.3.bcf).

For example:
```rust
use tokio::fs::File;
use tokio::io::Result;

use noodles_bcf as bcf;

#[tokio::main]
async fn main() -> Result<()> {
    let mut reader = File::open("vcf-spec-v4.3.bcf").await.map(bcf::AsyncReader::new)?;
    reader.read_file_format().await?;
    reader.read_header().await?;

    let mut record = bcf::Record::default();

    println!("{:?}", reader.read_record(&mut record).await);
    println!("{:?}", reader.read_record(&mut record).await);

    Ok(())
}
```
Prints:

```
Ok(91)
Err(Custom { kind: UnexpectedEof, error: "early eof" })
```

Is this the intended behaviour?

**Comment by zaeleus** [comment]
Thanks! This is fixed in 4300626002bbe23dff1ac645565ceba63275236b. It only affected the async reader.
