### ISSUE TITLE
[VCF] Parser didn't realy parse INFO header

### ISSUE THREAD

**Issue by natir** [zaeleus/noodles#80]
Hello,

First thank for your work on noodles.

I work with vcf without classic Info field.

For example:
```
##INFO=<ID=bwa_freebayes,Number=2,Type=String,Description="Variant calling method.">
```
Are parse in:
Key: `Other("bwa_freebayes", Count(1), String, "")`
Value: `Info { id: Other("bwa_freebayes", Count(1), String, ""), number: Count(2), ty: String, description: "Variant calling method.", idx: None, fields: {} }`

The problem appears when we parse the data, the `number` value use to parse value is key `number` not value `number`, so data should parse as string array are parse as string, check [Value::from_str_key code](https://github.com/zaeleus/noodles/blob/master/noodles-vcf/src/record/info/field/value.rs#L152)

One solution could not use Key `number` but Value `number` when we parse value other solution could improve Info Header parsing.

Again thank for your work and if you want I can help by work on improve header parsing.

**Comment by zaeleus** [comment]
Thanks! This is now fixed so that both info (0f9c7e4302e990bf8eca35f04df9b6adab057d1d) and genotype (4e78a8d8d6054d0fd8023a422c148805cb397620) fields prioritize using header records for type information. Keys no longer have that information attached.
