### ISSUE TITLE
mmCIF/pdbX Support

### ISSUE THREAD

**Issue by multimeric** [zaeleus/noodles#83]
I'm interested in implementing support for the mmCIF format which is used for molecular structures. I'm not certain if there is a formal standard, but it's fairly comprehensively defined here: https://pdb101.rcsb.org/learn/guide-to-understanding-pdb-data/beginner%E2%80%99s-guide-to-pdb-structures-and-the-pdbx-mmcif-format.

One challenge with this format is that it's quite flexible compared to the average tabular text format like VCF, BED etc, so I wonder if it would work well in the existing framework or not.

I'm open to implementing this when I get time, but I wanted to do an initial check before I get started.

**Comment by zaeleus** [comment]
Thanks for asking, @multimeric. noodles currently focuses on [HTS formats](https://samtools.github.io/hts-specs/); there are no plans to add support for PDBx/mmCIF.

**Comment by multimeric** [comment]
Fair enough.

**Comment by brainstorm** [comment]
@multimeric, I've been following your work here and thought that perhaps [Rust-Bio](https://github.com/rust-bio/rust-bio/) might be more fitting as it's a bit more general purpose than noodles?
