### ISSUE TITLE
Use of rayon for multithreaded applications

### ISSUE THREAD

**Issue by claymcleod** [zaeleus/noodles#85]
Hey @zaeleus,

I was using noodles-bam within a computationally bound program I'm writing. It's a simple map-reduce type application that loops over the reads in a BAM file. When I was researching the best way to introduce efficient multithreaded work for computationally bound problems in Rust, I found that [rayon] was highly recommended.

Looking at the BAM reader class, I see you implement the `std::iter::Iterator` trait for records: https://github.com/zaeleus/noodles/blob/master/noodles-bam/src/reader/records.rs#L30. Just wondering what your opinion is on adding in support for rayon's `par_iter()` (or comparable) for multithreaded work (where appropriate throughout noodles).

[rayon]: https://github.com/rayon-rs/rayon

**Comment by zaeleus** [comment]
Concurrency is enabled by async Rust and the `async` feature, which allows you to leverage [streams] instead of iterators, e.g., a basic map (apply `f`) and reduce (a summation):

```rust
use std::{env, thread};

use futures::{StreamExt, TryStreamExt};
use noodles::bam;
use tokio::{fs::File, io};

async fn f(_: bam::Record) -> Result<usize, io::Error> {
    Ok(1)
}

#[tokio::main]
async fn main() -> io::Result<()> {
    let src = env::args().nth(1).expect("missing src");

    let mut reader = File::open(src).await.map(bam::AsyncReader::new)?;
    reader.read_header().await?;
    reader.read_reference_sequences().await?;

    let worker_count = thread::available_parallelism().map(usize::from)?;

    let n = reader
        .records()
        .map(|result| result.map(f))
        .try_buffer_unordered(worker_count)
        .try_fold(0, |sum, n| async move { Ok(sum + n) })
        .await?;

    println!("{}", n);

    Ok(())
}
```

There are no plans to add an additional thread pool to noodles.

[streams]: https://docs.rs/futures/latest/futures/stream/index.html

**Comment by claymcleod** [comment]
Thanks for the example code. I did try it, and, unfortunately, I did not get any speed up in my performance. I'm going to keep going down that path for a bit to see where it leads because, admittedly, I'm not an expert on Rust's specific `async`/`await` environment (or `tokio` specificially).

> **Concurrency** is enabled by async Rust and the `async` feature

That said, I wonder if this is the key—my understanding is that Tokio enables concurrency and not parallelism, and thus it would be an appropriate solution for IO-bound problems but not CPU-bound problems. This viewpoint is basically informed by my scanning of the docs and then my experience running your example:

- [Here](https://tokio.rs/tokio/tutorial#when-not-to-use-tokio), the docs point out that Tokio is not designed to speed up CPU bottlenecks. From the language they used there, I assumed that the `async`/`await` works similarly to those keywords in other languages, i.e. introducing concurrency.
- I also saw [this snippet](https://tokio.rs/tokio/tutorial/spawning#concurrency) in the tutorial where they further suggested it provides concurrency and not parallelism (though, admittedly, they are building up a naive example here so they may just not have gotten to the parallelism part).
- Looks like the most important method to this discussion from your example is [`try_buffer_unordered`](https://docs.rs/futures/latest/futures/stream/trait.TryStreamExt.html#method.try_buffer_unordered). From the docs, this method appears to be doing things in a concurrent fashion. Though you select the number of cores detected on the host machine as the `n` argument, the process never eclipses more than 125% utilization, which is what I'd expect in the case of concurrency.

<img width="570" alt="Screen Shot 2022-04-29 at 11 48 52 PM" src="https://user-images.githubusercontent.com/3411613/166091555-2dde0c6f-1fa5-404a-82be-2a01e7acf4da.png">

All that to say, I think it's a smart decision to stick with `async`/`await` in most cases, as most genomics problems are IO-bound as we've discussed. Further, it likely makes sense to not confound noodles with another library like `rayon`. If my understanding above is correct, the question of "what is the canonical way to introduce parallelism using noodles?" still remains. 

The two ways I can see are (a) reading everything into memory and then starting your parallel work, or the smarter but a bit more intensive (b) roll your own threadpool solution whereby one threads reads through the iterator and pushes records onto a mutex protected queue and the other threads pull work from the queue.

**Comment by claymcleod** [comment]
This is also a relevant discussion, and it was the direction I was looking in: https://docs.rs/tokio/latest/tokio/#cpu-bound-tasks-and-blocking-code. Before I had read this, I had gone down the route of creating my own runtime using `tokio::runtime::Builder::new_multi_thread()` when I adapted your example. The results were still disappointing, so I don't think I have that figured out yet. Either that, or the solution is just not the right for for my problem:

> It is also possible to create an extra Tokio runtime dedicated to CPU-bound tasks, but if you do this, you should be careful that the extra runtime runs only CPU-bound tasks, as IO-bound tasks on that runtime will behave poorly.

**Comment by claymcleod** [comment]
I've added a CPU intensive load to your example, rewrote it without async using `rayon`, and then compared the results. Let me know what you think. Ultimately, I think I could use this chunking strategy to balance memory consumption versus parallelism (and without needing any additions to noodles).

## Original Example

Max CPU was 100%.

```rust
use std::{env, thread};

use futures::{StreamExt, TryStreamExt};
use noodles_bam as bam;
use tokio::{fs::File, io};

async fn f(record: bam::Record) -> Result<u128, io::Error> {
    // Intentionally wasteful operation to allow CPU time to stack up
    let mut result: u128 = 0;
    for i in 0..1_000_000 {
        result += record.clone().sequence_mut().to_string().len() as u128
    }

    Ok(result)
}

#[tokio::main]
async fn main() -> io::Result<()> {
    let src = env::args().nth(1).expect("missing src");

    let mut reader = File::open(src).await.map(bam::AsyncReader::new)?;
    reader.read_header().await?;
    reader.read_reference_sequences().await?;

    let worker_count = thread::available_parallelism().map(usize::from)?;

    let n = reader
        .records()
        .map(|result| result.map(f))
        .try_buffer_unordered(worker_count)
        .try_fold(0, |sum, n| async move { Ok(sum + n) })
        .await?;

    println!("{}", n);

    Ok(())
}
```

## Using `rayon`

Maxmimum CPU was 750%.

```rust
use std::{env, fs::File, io};

use itertools::Itertools;
use noodles_bam as bam;
use rayon::prelude::*;

fn f(record: &bam::Record) -> u128 {
    // Intentionally wasteful operation to allow CPU time to stack up
    let mut result: u128 = 0;
    for i in 0..1_000_000 {
        result += record.clone().sequence_mut().to_string().len() as u128
    }

    result
}

fn main() -> io::Result<()> {
    let src = env::args().nth(1).expect("missing src");

    let mut reader = File::open(src).map(bam::Reader::new)?;
    reader.read_header()?;
    reader.read_reference_sequences()?;

    let chunk_size = 100000;
    for chunk in &reader.records().into_iter().chunks(chunk_size) {
        let batch: Vec<bam::Record> = chunk.map(|x| x.unwrap()).collect();
        let result: u128 = batch.par_iter().map(|r| f(r)).sum();
        println!("Total sequence length for this chunk: {:?}", result);
    }
    Ok(())
}
```

**Comment by claymcleod** [comment]
In researching the above, I was able to find something that works relatively well for my use case and wouldn't require any additions to `noodles`:

```rust
use std::{env, fs::File, io};

use itertools::Itertools;
use noodles::bam;
use rayon::prelude::*;

fn f(record: &bam::Record) -> u128 {
    // Intentionally wasteful operation to allow CPU time to stack up
    let mut result: u128 = 0;
    for _i in 0..1_000_000 {
        result += record.clone().sequence_mut().to_string().len() as u128
    }

    result
}

fn main() -> io::Result<()> {
    let src = env::args().nth(1).expect("missing src");

    let mut reader = File::open(src).map(bam::Reader::new)?;
    reader.read_header()?;
    reader.read_reference_sequences()?;

    const CHUNK_SIZE: usize = 100000;
    for chunk in &reader.records().into_iter().chunks(CHUNK_SIZE) {
        let batch: Vec<bam::Record> = chunk.map(|x| x.unwrap()).collect();
        let result: u128 = batch.par_iter().map(|r| f(r)).sum();
        println!("Total sequence length for this chunk: {:?}", result);
    }
    Ok(())
}
```

**Comment by afontenot** [comment]
> I was able to find something that works relatively well for my use case and wouldn't require any additions 

This worked really well for me too, thanks. Found this by searching.

For others trying to adapt this approach, notice that the specific way `reader` is created sidesteps an issue. The method of opening files recommended by the documentation,

```rust
let mut reader = vcf::io::reader::Builder::default().build_from_path("sample.vcf")?;
```

results in an opaque type that the Rayon `.par_iter` methods aren't implemented on. If you build the reader yourself with something like what's shown in the example above, or what I use for VCF files:

```rust
let mut reader = File::open(args.vcf).map(std::io::BufReader::new).map(vcf::io::Reader::new)?;
```

you can chain together Rayon's iterators like `reader.records().par_bridge()` with no problem!

I see a ~4x speedup over single-threaded even without implementing chunking, just doing one Rayon threaded call per record. This limit appears to be due to reading VCF records sequentially from disk with noodles, not an inefficiency of per-record parallelization with Rayon. (Also note that the chunking shown in @claymcleod's example doesn't improve efficiency, because each chunk is being *sequentially* parallelized on a per-record basis.)
