### ISSUE TITLE
Working with FASTA sequences

### ISSUE THREAD

**Issue by claymcleod** [zaeleus/noodles#86]
Would it be possible for us to add some convenience methods added to [`noodles_fasta::record::Sequence`](https://github.com/zaeleus/noodles/blob/master/noodles-fasta/src/record/sequence.rs)? I'm hoping to be able to do the following:

```rust
// Setup
let mut reader = File::open(&reference)
    .map(BufReader::new)
    .map(fasta::Reader::new)?;
let index = fai::read(reference.with_extension("fa.fai"))?;
let mut adapter = IndexedReader::new(reader, index);
let chr1 = adapter.get("chr1");

if let Some(res) = adapter.get("chr1") {
    let chr1 = res?;
    let start = Position::try_from(100000).unwrap();
    let end = Position::try_from(100050).unwrap();
    if let Some(r) = chr1.sequence().get(start..=end) {
        // (1) Is this the intended way to turn a `[u8]` to a string? It seems overkill as the alphabet's are do not
        //     need the range that utf-8 provides (usually falls within ASCII). The only other way I am aware of to
        //     do it is to map them to a Vec<char>, which might be a better choice in hindsight. Regardless, should
        //     noodles offer a convenience method that points you to the canonical way?
        println!("{:?}", String::from_utf8_lossy(r));

        // (2) Something like this for reverse compliment—seems like a common operation you'd want to do for
        //     a sequence.
        println!("{:?}" r.reverse_compliment());
    }
}
```

**Comment by claymcleod** [comment]
Another suggestion: could we make [`LINE_BASES`](https://github.com/zaeleus/noodles/blob/master/noodles-fasta/src/writer.rs#L5) configurable for the writer?

**Comment by zaeleus** [comment]
1. When working with alleged byte strings, you can use [bstr] to wrap it before printing it as a string, e.g., [playground]. It's highly unlikely that the sequence ever needs to be a string.
2. `Sequence` has an undefined alphabet, which makes this tricky. What is the expected outcome for characters outside the IUPAC DNA/RNA alphabet or for amino acid (protein) sequences?

[bstr]: https://docs.rs/bstr/0.2.17/bstr/index.html
[playground]: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=069d46e020ec7a98c53720dae052476a

**Comment by claymcleod** [comment]
1. Okay will do that, thanks for the tip.
2. That’s a really good question. After a few moments thought, I would probably wrap it in a `Result` and let the user decide what to do. In that case, it would be important to return a new `Sequence` and not edit the existing `Sequence` in place. I would think that’s reasonable, given that it would work well for most use cases I can think of.

**Comment by claymcleod** [comment]
Oh, just realized I'm still waiting on your thoughts on number 2 above. I'll let you close this when you're ready.

**Comment by zaeleus** [comment]
I'll add an iterator with fallible conversions to complement the sequence.

**Comment by zaeleus** [comment]
In your example, you can use [`std::ops::RangeFull`](https://doc.rust-lang.org/std/ops/struct.RangeFull.html) to denote the entire sequence, i.e., `seq.get(..)`, which returns a byte slice (`&[u8]`). Alternatively, the underlying byte slice is available via [AsRef<[u8]> for Sequence](https://docs.rs/noodles/0.100.0/noodles/fasta/record/struct.Sequence.html#impl-AsRef%3C%5Bu8%5D%3E-for-Sequence).

And thanks for the feedback. For more discourse on ergonomics, I recommend starting [a discussion](https://github.com/zaeleus/noodles/discussions) with a question and/or request for examples.
