### ISSUE TITLE
Extracting the uint value from a Position

### ISSUE THREAD

**Issue by LukaP-BB** [zaeleus/noodles#88]
Is it possible to get the Position of a bam::Record as an int, in order to do some operations with this position ?
I could not find any methods allowing this in the docs.
Sorry if this is a noob question, I'm still very new to rust.

**Comment by zaeleus** [comment]
[`bam::Record::position`]/[`sam::AlignmentRecord::alignment_start`] returns an `Option<Position>`. The [`Option`] means that the record may or may not be mapped to any position on the reference sequence, and [`Position`] means that, if set, the position is normalized to be 1-based. You can get the underlying `usize` using standard conversion methods (i.e., `From<Position> for usize`):

```rust
if let Some(alignment_start) = record.alignment_start() {
    let position = usize::from(alignment_start);
    // ...
}
```

[`bam::Record::position`]: https://docs.rs/noodles/0.22.0/noodles/bam/struct.Record.html#method.position
[`sam::AlignmentRecord::alignment_start`]: https://docs.rs/noodles/0.22.0/noodles/sam/trait.AlignmentRecord.html#tymethod.alignment_start
[`Option`]: https://doc.rust-lang.org/std/option/enum.Option.html
[`Position`]: https://docs.rs/noodles/0.22.0/noodles/core/struct.Position.html

**Comment by LukaP-BB** [comment]
Thank you very much for your answer, it poped up as I was writing a follow up to my question :D
I managed to find a solution in the meantime, that looks like this : 
```rust
let mut cursor_pos : usize = record.position().unwrap().into();
```
This is obviously less optimal since it doesn't handle all cases, and I will use your suggestion instead.
