### ISSUE TITLE
How to convert vcf::record::Position to core::Position 

### ISSUE THREAD

**Issue by curoli** [zaeleus/noodles#89]
Hello,

Sorry, but this is very frustrating. Why does a single library need different types of Position? To query a tabix Index, I need an Interval made of core::Positions, but then I get records that have a vcf::record::Position, and I can't figure out how to convert one into the other.

Thanks!

Best, Oliver

 ```
Checking phenics v0.1.2 (/mnt/c/Users/oliverr/git/phenics)
error[E0308]: mismatched types
  --> src/tabix.rs:28:54
   |
28 |                 if config.region.interval().contains(&record.position()) {
   |                                                      ^^^^^^^^^^^^^^^^^^ expected struct `noodles::noodles_core::Position`, found struct `noodles::noodles_vcf::record::Position`
   |
   = note: expected reference `&noodles::noodles_core::Position`
              found reference `&noodles::noodles_vcf::record::Position`

```

**Comment by zaeleus** [comment]
This is because the position field in VCF can either indicate a reference position or a telomere. It is not necessarily a valid position (see [§ 1.6.1.2]).

You can convert from `vcf::record::Position` to `noodles_core::Position` using the underlying types:

```rust
fn vcf_position_to_core_position(
    position: vcf::record::Position,
) -> Result<noodles_core::Position, noodles_core::position::TryFromIntError> {
    usize::try_from(i32::from(position)).and_then(noodles_core::Position::try_from)
}
```

```rust
let position = vcf_position_to_core_position(record.position())?;

if region.interval().contains(&position) {
    // ...
}
```

[§ 1.6.1.2]: https://samtools.github.io/hts-specs/VCFv4.3.pdf#subsubsection.1.6.1

**Comment by curoli** [comment]
Thanks for the quick response! I didn't know this was possible, I already thought of converting to String and parsing it. Two-step conversion via i32 is not too bad, although I feel there should be a single conversion for it.

**Comment by zaeleus** [comment]
`vcf::record::Position` is now backed by a `usize` in noodles-vcf 0.16.0. This simplifies the conversion to `noodles_core::Position`: `Position::try_from(usize::from(position))`.
