### ISSUE TITLE
Async io and memory mapped file support?

### ISSUE THREAD

**Issue by andy-thomason** [zaeleus/noodles#9]
This is an excellent project which shows off the capabilities of Rust in a bioinfomatics environment.

I was wondering if you plan async or memory mapped file support?

The two most common use cases are:

Data on local SSD -> Memory mapped files (you can get away with Cursor if performance is not an issue).
Data on object store -> async file i/o.

Async requires use of AsyncRead/AsyncWrite and async functions.

With BGZip encoded data, you can read ahead on multiple async requests (s3 recommends
around 16MB chunks) and decode on multiple threads to lower latency and memory usage.

On writes, you can use multipart upload on s3.

I'd be happy to help if you have not already done some of this.

**Comment by zaeleus** [comment]
Hi, @andy-thomason!

Those are good questions! I don't have any immediate plans for either memory-mapped I/O or an async API. I understand the potential benefits, but I'd have try some experiments before making a call.

**Comment by andy-thomason** [comment]
Thanks! I might make a PR or two, but have to get my work peer reviewed at work before making submissions.

For example, adding Plink **bim**, **bam**, **bed** might be useful for us in the short term and pgen/bgen in the longer span.

**Comment by andy-thomason** [comment]
We can also integrate with R through **extendr** which might be useful.
