### ISSUE TITLE
"invalid genotypes: invalid genotype: empty input"

### ISSUE THREAD

**Issue by curoli** [zaeleus/noodles#94]
Hello,

After upgrading from 0.23.0 to 0.24.0, I'm seeing a lot of these errors with code that worked before:

```
invalid genotypes: invalid genotype: empty input
```

I'm using a `noodles::vcf::Reader` wrapping a `noodles::bgzf::Reader` wrapping my custom reader. Thanks!

Best, Oliver

**Comment by zaeleus** [comment]
There are no major changes between 0.23.0 and 0.24.0, so I'm surprised this would happen. Can you share a minimal example that fails?

**Comment by zaeleus** [comment]
I'm closing this as stale. The genotypes parser has been improved since this issue, so do tell if you're still receiving the error.
