### ISSUE TITLE
Genbank support?

### ISSUE THREAD

**Issue by jimrybarski** [zaeleus/noodles#95]
Is there any interest in adding support for genbank? Is anyone already working on it somewhere?

**Comment by brainstorm** [comment]
AFAIK this repo covers [hts-specs](https://github.com/samtools/hts-specs/) formats primarily. There's prior art w/ GenBank and Rust though, after a quick search I found:

1. https://github.com/dlesl/gb-io
2. https://github.com/jperkel/gb_read

There's also [rust-bio](https://github.com/rust-bio/rust-bio/), which is my default go-to for bioinformatics algorithms and data structures in Rust, but there doesn't seem to be much GB-specific code nowadays.

Hope that helps!

**Comment by zaeleus** [comment]
Hi, @jimrybarski. As mentioned, noodles focuses on formats mainly described by [hts-specs](https://samtools.github.io/hts-specs/). There is no plan to add GenBank support.
