### ISSUE TITLE
Compression level 0 may result in corrupted BGZF file

### ISSUE THREAD

**Issue by wjv** [zaeleus/noodles#96]
According to the [BGZF spec](https://samtools.github.io/hts-specs/SAMv1.pdf) (p. 13, bottom), `ISIZE` (the uncompressed size of a data block) and `BSIZE` (the full size of a data block including headers, compressed data and footers) should both be <= 65536. `ISIZE` is stored in the footer of a block as a u32, and `BSIZE` in the BGZF-specific header subfield as a u16.

When a compression level of 0 is selected for the output, it's possible — probable, even — that `BSIZE` will be larger than `ISIZE`. Currently (if I read the code correctly), noodles will impose a limit of 65536 bytes on `ISIZE` but does not check the resultant `BSIZE` while writing BGZF. When `bsize` is [downcast to a u16 ](https://github.com/zaeleus/noodles/blob/9dac00e8103da7fed28f931ab8b0262419d12b28/noodles-bgzf/src/writer.rs#L284)before being written to the BGZF header, it may therefore be truncated, rendering the entire file ill-formed. (Easy to check with `bgzip -t`.) 

Note that it is desirable to have the ability to write uncompressed BAM output, especially for use in processing pipelines.

Apologies for no patch, but there is probably a decision to be made as to *how* to tackle this issue. I've looked at some other libraries, and implementations differ. For instance, the [`bam` crate](https://crates.io/crates/bam) seemingly just splits a block in two if it detects the compresses size has become too large!

Thanks to @jch-13 for helping me chase down this issue!

**Comment by zaeleus** [comment]
Thanks for reporting!

Looking at other prior work, HTSJDK reduces the max uncompressed write buffer to [65498 bytes] (-38 bytes), and (empirically) I'm seeing HTSlib is maxing out at 65280 bytes (-256 bytes). The simplest solution would be to take an approach like this as well.

It is still possible for the compression of a DEFLATE implementation to be _larger_ than its input, but for now, to prevent the `BSIZE` cast from truncation, it is now checked and throws an error ([e72f5ea](https://github.com/zaeleus/noodles/commit/e72f5ea0a9c4a025d0394464079e27abf558dbb3) and [4de1c4d](https://github.com/zaeleus/noodles/commit/4de1c4dcafa9429fb619b6ebb63a02e194fd1241)).

[65498 bytes]: https://github.com/samtools/htsjdk/blob/489c4192dd9682a9d1e53f4c8f6f7bb826e33589/src/main/java/htsjdk/samtools/util/BlockCompressedStreamConstants.java#L55

**Comment by wjv** [comment]
Great! Thanks for the quick response! That sounds like a very pragmatic and workable solution.

We had an internal discussion about how one would ideally solve this, and we felt that keeping track of both uncompressed and compressed stream size in real time would be a hard problem, and likely not worth the overhead, leading us to think that a more pragmatic approach would probably be preferred. As we all seem to have found, this also seems to have been the conclusion other implementors had come to!

I have to admit I also haven't looked into how htslib (as the reference implementation) solves this issue… that's just too much C to read on an empty stomach! 😬

**Comment by zaeleus** [comment]
I recorded how much DEFLATE overhead there is for 65536 bytes of data at compression level 0 using the supported flate2 backends and a modified libdeflater to allow level 0.

| backend               | overhead (bytes) |
|-----------------------|-----------------:|
| miniz_oxide 0.5.3     |               15 |
| zlib 1.2.11           |               10 |
| cloudflare/zlib 1.2.8 |               10 |
| zlib-ng@[8568840]     |               10 |
| libdeflate 1.10       |               10 |

[8568840]: https://github.com/zlib-ng/zlib-ng/tree/856884022cc7202b159ba76c8e89bb1d9f7300d5

05099805aec3734d5b9681b2c2a5798c9abb46f8 reduces the default block write buffer size to 65495 bytes, using max `ISIZE` - BGZF header size - gzip trailer size - max(overheads), i.e., 65536 - 18 - 8 - 15. This, at least, allows compression level 0 to work correctly now.
