### ISSUE TITLE
Setting Contig length

### ISSUE THREAD

**Issue by mbhall88** [zaeleus/noodles#99]
Excuse my ignorance if I am missing something obvious, but how can I create a new [`vcf::header::Contig`](https://docs.rs/noodles/latest/noodles/vcf/header/struct.Contig.html#) and set its length at the same time?

The `new` constructor only takes an id. I know I can construct with the the struct syntax `Contig {}`, but I then have to set the other attributes (or use defaults).

Am I missing some other more common way of doing this?

**Comment by zaeleus** [comment]
There is currently no way to set field values or mutate a VCF header record.

For `vcf::header::Contig`, I have planned to remove length as a special field, given it is nonstandard. Though, this would require better support for retrieving/inserting other fields.

In the interim, I'll add a mutable getter for the length (`Contig::len_mut`) to at least allow it to be set after construction.
